### ISSUE TITLE
bad casing of table name when creating the down migration

### ISSUE THREAD

**Issue by ami-m** [doctrine/DoctrineMigrationsBundle#100]
In my orm file I use the 'table' key to specify an all lowercase name of the table.

But when the migration is created, the expressions in the down migration are camel cased (like the entity name). In the up migration the name (and the casing) is correct.

**Comment by stof** [comment]
The SQL for migrations comes from the DBAL project itself, not from this bundle (which contains no logic at all but only integrates the Doctrine Migrations project with Symfony)
