### ISSUE TITLE
Random indexes names

### ISSUE THREAD

**Issue by crash21** [doctrine/DoctrineMigrationsBundle#101]
I have exactly this issue here:

http://stackoverflow.com/questions/18915841/weird-random-names-in-constrains-generated-by-doctrine2-symfony2

Even though I use

 * @ORM\Table(name="foo", indexes={@ORM\Index(name="fk_foo_category1_idx", columns={"idcategory"})})

it generates random FKs like FK_3B112B06AC9951CC

**Comment by stof** [comment]
This should be reported to the Doctrine ORM project, as it is the one producing the SQL. And btw, I think it has been fixed in the ORM 2.5 (currenly in alpha).

I'm closing the issue as it is not related to this bundle
