### ISSUE TITLE
Default value for field type timestamp in MySQL platform

### ISSUE THREAD

**Issue by saimon7** [doctrine/DoctrineMigrationsBundle#103]
Why we can't add default value for field type timestamp like "CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP", only CURRENT_TIMESTAMP.

**Comment by stof** [comment]
This bundle is only integrating the migrations library into Symfony. There is no logic in the bundle at all.

And the SQL itself is not even generated by the Doctrine Migrations library but by Doctrine DBAL itself. So please report it to the DBAL issue tracker (however, given that it is supported by MySQL only, I doubt the DBAL team will implement it). I'm closing this issue as it is not related to the bundle
