### ISSUE TITLE
doctrine:migrations:diff is generating SQL for MEDIUMTEXT fields

### ISSUE THREAD

**Issue by jamestooks** [doctrine/DoctrineMigrationsBundle#104]
The diff command is generating SQL everytime even if the database is already up to date.

For example:

- I run diff to generate SQL to update a field to now be a MEDIUMTEXT field
- I execute the migration
- I run diff again and the same SQL is generated again

**Comment by stof** [comment]
This should be reported against the DBAL project, which is responsible for comparing schemas and generating the list of SQL queries needed to go from one to the other.
