### ISSUE TITLE
Support for Symfony > 2.1

### ISSUE THREAD

**Issue by jspizziri** [doctrine/DoctrineMigrationsBundle#108]
Is there any intent to update this for symfony releases > than 2.1?

For instance 2.3 is the latest LTS release, and the next LTS release (2.7) is on its way shortly.

**Comment by mikeSimonson** [comment]
There are plans.
We just lack the man power.
PR are welcomed.

**Comment by jspizziri** [comment]
Word :),

I can appreciate that. If I get some spare time I'll submit a PR.

**Comment by stof** [comment]
The master branch supports Symfony 2.1+ since years
