### ISSUE TITLE
Migrations don't keep track of the entity manager they were created with

### ISSUE THREAD

**Issue by spdionis** [doctrine/DoctrineMigrationsBundle#109]
The problem arises when an application deals with two (or more) databases with different schemas.

If you run `doctrine:migrations:diff --em=db1` and then `doctrine:migrations:migrate --em=db2` the migrations generated from db1 will be ran on db2.

I don't think this is intended behaviour? 
Of course you can manually modify the migrations and put $this->skipIf($this->connection->getDatabase() !== 'db1') at the moment but not the best way i think :).

**Comment by mikeSimonson** [comment]
What would be a better way ?

**Comment by spdionis** [comment]
Have the migrations "namespaced" by entity manager? I don't think there's a valid use case to use a migration created with one entity manager with another entity manager.

**Comment by mikeSimonson** [comment]
Well I don't think that namespacing is a solution and I can see example where I have 2 em for the  same connection but with different params. One is used to generate the diff and one is used to run it.

**Comment by spdionis** [comment]
Ok, that can be true. But i still think that by default a migration run should only use migrations created with the same entity manager (in case the `--em` option was used).

Maybe it's possible to at least add an option for this for `doctrine:migrations:diff`. Something like `--lock-to-manager`, I'm not sure about the naming tho.

**Comment by stof** [comment]
Closing as duplicate of #38
