### ISSUE TITLE
continuing issue no. 7

### ISSUE THREAD

**Issue by saggi18dec** [doctrine/DoctrineMigrationsBundle#11]
yes. configuration is done through config.yml files, but there is an option to provide configuration at runtime in the  command.
which is not working properly, and the issue is for that.

**Comment by jrobeson** [comment]
probably fixed in https://github.com/doctrine/DoctrineMigrationsBundle/issues/95 ?

**Comment by jrobeson** [comment]
@mikeSimonson : can this be closed too then?

**Comment by mikeSimonson** [comment]
I would prefer to close it only when test are made for that issue

**Comment by stof** [comment]
Closing becuase of https://github.com/doctrine/migrations/pull/219
