### ISSUE TITLE
Migration is taking too time .

### ISSUE THREAD

**Issue by ajeetvarma** [doctrine/DoctrineMigrationsBundle#110]
I have a migration script as given below  

           <?php

          namespace Wedmegood\Migrations;

            use Doctrine\DBAL\Configuration;
            use Doctrine\DBAL\DriverManager;
            use Doctrine\DBAL\Platforms\MySqlPlatform;
            use Doctrine\DBAL\Migrations\AbstractMigration;
            use Doctrine\DBAL\Schema\Schema;
            use Webmuch\VendorBundle\Entity\Vendor;
            use Webmuch\VendorBundle\Entity\VendorActiveStatus;
            use Webmuch\EntityBundle\Entity\Image;
            use Webmuch\EntityBundle\Entity\ImageTag;
            use Webmuch\EntityBundle\Entity\ImageInfo;
            use Webmuch\EntityBundle\Entity\ImageMetaInfo;

            /**
               * Auto-generated Migration: Please modify to your needs!
               */
          class VersionVendor extends AbstractMigration
           {
	           private function getEntityManager(){
                   global $kernel;

                    if ('AppCache' == get_class($kernel)) {
                    $kernel = $kernel->getKernel();
                    }

                   $em = $kernel->getContainer()->get('doctrine.orm.entity_manager');

                  return $em;
   	          }

                  public function up(Schema $schema)
                    {
                        $connection = DriverManager::getConnection(array(
		                    'dbname' => 'wedmegood',
		                     'user' => 'root',
		                     'password' => 'root',
		                     'host' => 'localhost',
		                      'driver' => 'pdo_mysql',
		                     'charset' => 'utf8',
		                    'driverOptions' => array(
		                     'pdo_mysql' => 'SET NAMES utf8')
		                    ), $config = new Configuration);
		                $queryBuilder = $connection->createQueryBuilder();

		                    $results = $queryBuilder->select('*')
                                         ->from('member', 'a')
                                        ->orderBy('a.id', 'ASC')
                                       ->execute()
                                      ->fetchAll();

        $em = $this->getEntityManager();

        for($i=0; $i<count($results); $i++){
        	if($results[$i]["user_type"] == "vendor" || $results[$i]["user_type"] =="Vendor Type"){
        		$vendor = new Vendor();
	        	$vendor->setName($results[$i]["name"]);
	        	$vendor->setPhone($results[$i]["phone"]);
	        	$vendor->setContact($results[$i]["contact_name"]);
	        	$vendor->setCompany($results[$i]["website"]);
	        	$vendor->setFacebookLink($results[$i]["fb_id"]);
	        	$vendor->setInformation($results[$i]["additional_info"]);
	        	$vendor->setMember($em->getRepository("UserBundle:User")->findOneBy(array('id' => $results[$i]["id"])));
	        	$vendor->setVendorType($em->getRepository("EntityBundle:VendorType")->findOneBy(array('id' => $results[$i]["vendor_type"])));
	        	$vendor->setMembership($em->getRepository("EntityBundle:Membership")->findOneBy(array('id' => $results[$i]["membership_id"])));

	        	$vendorActiveStatus = new VendorActiveStatus();
	        	$vendorActiveStatus->setVendor($vendor);
	        	if($results[$i]["show_on_home"] == "Yes"){
	        		$vendorActiveStatus->setShowOnHome(true);	
	        	} else {
	        		$vendorActiveStatus->setShowOnHome(false);
	        	}
	        	if($results[$i]["show_on_vendor_page"] == "Yes"){	
	        		$vendorActiveStatus->setShowOnVendor(true);	
	        	} else {
	        		$vendorActiveStatus->setShowOnVendor(false);
	        	} 
	        	
	        	$vendorActiveStatus->setShowOnSearch($results[$i]["show_on_searcmore"]);	
	        	
	        	if($results[$i]["show_contact_details"] == "Yes"){	
	        		$vendorActiveStatus->setShowContactDetails(true);	
	        	} else {
	        		$vendorActiveStatus->setShowContactDetails(false);
	        	} 

	        	$image = new Image();
	        	$image->setName($results[$i]["profile_image"]);
	        	$image->setThumb570($results[$i]["thumb_status"]);
	        	$image->setThumb150($results[$i]["thumb_status"]);
	        	$image->setThumb1200($results[$i]["thumb_status"]);

	        	$imageInfo = new ImageInfo();
	        	$imageInfo->setImage($image);
	        	$imageInfo->setUploadedDate(new \DateTime($results[$i]["created_date"]));
	        	$imageInfo->setUploadedBy($vendor->getMember());

	        	$imageTag = new ImageTag();
	        	$imageTag->setImage($image);

	        	$imageMetaInfo = new ImageMetaInfo();
	        	$imageMetaInfo->setImage($image);

	        	$vendor->setVendorImagePath($imageInfo);

	        	$em->persist($image);
	        	$em->persist($imageTag);
	        	$em->persist($imageInfo);
	        	$em->persist($imageMetaInfo);
	        	
	        	$em->persist($vendorActiveStatus);
	        	$em->persist($vendor);

	        	$em->flush();
        	}
        }    
    }

          public function down(Schema $schema)
          {
                // this down() migration is auto-generated, please modify it to your needs

             }
          }

In My old database table 10000 data's are available and it is taking too time while it is not much huge data . I am doing migration after breaking up old data in limit of 1000 each time then it is taking 5 to 6 minutes each time . Is any way to speed up migration very fast ?

Any help will be very much appreciated .

Thanks a lot !!

**Comment by stof** [comment]
anything using the EntityManager will indeed be slow (you should use SQL for your migration), but more important it will be very fragile: your migration works only when it is the latest migration. If you have several non-applied migration, the first one will break because the EntityManager will work with the current code and mapping, not with the mapping at the time the DB migration was written

**Comment by stof** [comment]
btw, you don't need to create a new DB connection like you are doing. You have access to the DB connection sued for migrations through ``$this->connection``

**Comment by mikeSimonson** [comment]
The only way to make that code fast is to convert your object oriented logic into sql statement with the appropriate indexes.

**Comment by ajeetvarma** [comment]
K , Thanks to all , i got it , i have fixed my problem by using SQL rather than using Entity Manager ..
