### ISSUE TITLE
Drop primary key migration

### ISSUE THREAD

**Issue by supertanuki** [doctrine/DoctrineMigrationsBundle#123]
I wanted to drop a primary key. The migration was:

```php
        $this->addSql('ALTER TABLE mytable DROP PRIMARY KEY');
```

But I have an Exception.
I fix the problem by adding this line before the drop primary key :

```php
        $this->addSql('ALTER TABLE mytable MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE mytable DROP PRIMARY KEY');
```

**Comment by mikeSimonson** [comment]
This is not a bug in doctrine migrations, it all depends on the database that you use and the statements you use.
