### ISSUE TITLE
doctrine/migrations latest version does not support php versions below 5.4

### ISSUE THREAD

**Issue by markokeeffe** [doctrine/DoctrineMigrationsBundle#124]
Due to the dependency in composer.json: 
    
    "doctrine/migrations": "~1.0@dev"

Running composer update results in the following error:

    Problem 1
        - doctrine/migrations dev-master requires php >=5.4.0 -> your PHP version does not satisfy that requirement.
        - doctrine/migrations dev-master requires php >=5.4.0 -> your PHP version does not satisfy that requirement.
        - Installation request for doctrine/migrations dev-master -> satisfiable by doctrine/migrations[dev-master].

The dev version of doctrine/migrations requires PHP5.4 since 27th June: https://github.com/doctrine/migrations/commit/0e60856a10e8b510daa612fe25f6245aece77e68

Switching the dependency to:

    "doctrine/migrations": "1.0.0-alpha3"

Would fix the problem.

**Comment by stof** [comment]
Well, we won't forbid using update version of the library.

PHP 5.3 reached its end of life 1 year ago and stopped received non-security bug fixes 2 years ago: http://php.net/supported-versions.php So it seems totally legitimate for the maintainer of ``doctrine/migrations`` to require using at least PHP 5.4 (which will itself stop receiving security patches in 1 month btw).
I'm closing this issue as "Won't fix".
