### ISSUE TITLE
Problem with version 2.1.x

### ISSUE THREAD

**Issue by selossevianney** [doctrine/DoctrineMigrationsBundle#125]
Hello,

I have an issue with this bundle version. I was using 2.1.x@dev but now, composer can't find a matching version anymore. I'm afraid to take a previous version because I don't think my requirements matches. So, What can I do now?

**Comment by odino** [comment]
Can you try with 1.x?

**Comment by selossevianney** [comment]
Yes, I'll try but since I have seen "symfony/symfony: >=2.0,<2.1" for 2.0.x , my question is, Which version of Symfony is used for this bundle with 1.x version ? 

I use 2.6 version of Symfony, will I have a problem with 1.x version ?
