### ISSUE TITLE
Configuring which finder to use

### ISSUE THREAD

**Issue by liquorvicar** [doctrine/DoctrineMigrationsBundle#127]
It looks like DoctrineMigrations now supports different Finder strategies for loading the actual migrations but I can't see a way to configure which one to use in the bundle. Am I missing something?

**Comment by mikeSimonson** [comment]
@liquorvicar I don't think that the doctrine migration bundle has an option to configure that but honestly we kept it more to ensure that if hell breaks loose (hear the new implementation breaks someone implementation or use case) we have a backup solution.

Until now no one has had any issue that wasn't fixable in the new implementation.

**Comment by liquorvicar** [comment]
So not sure I understand your reply (maybe I'm missing the point on the Finder feature!) I was under the impression that the Finders was a new feature in MIgrations (https://github.com/doctrine/migrations/commit/1dab0785ddbf61749918d0097f7032ec5071f18c) that allowed us to set different strategies for how the Migration classes are named stored etc Is that not right?

If that is the case, I'm happy to do a PR to be able to configure this in the bundle! We would like to determine our own naming strategy for Migration classes (might well be able to contribute that strategy back to the main Migrations package as well).

**Comment by mikeSimonson** [comment]
Well if you want to ship your own finder, feel free to do so.

Out of curiosity, what would be different in your naming strategy ?

**Comment by liquorvicar** [comment]
There's a couple of points we'd like to implement (and I'm not sure all these are currently possible even with the Finder strategy):
- we'd like the Migrations to have a more human-readable name, e.g. Project0001AddInitialSchema, Project0002AddFeature etc
- we're also using Migrations to manage test/dev data and reference data so we have two levels of Migrations: production migrations including the schema and any production reference data, and dev migrations that include any test/dev data. Currently the way we do it is to extend every production migration with a dev migration and use the dev directory in dev. This is a bit labour intensive so I'd like a way to be able to override (extend) production migrations only if needed. So some kind of Finder to merge two directories conditionally would be along the lines of what we need.

**Comment by mikeSimonson** [comment]
So you can already name your migration something like Version00001FeatureBla with the default Finder. I don't think it's a good idea to have the project name show up in the migration name.

If you need dev and prod stuff, it makes more sense to have mutliple migration configuration for your application.
The default could be the production one and another migrations configuration could hold everything that's related to the development.
In that use case you just need to run the migration with the default configuration for production
And in dev you would just need to also run the migration with both your dev configuration and the default one.

Does this makes sense to you ?

**Comment by liquorvicar** [comment]
Having "Project" at the beginning was just to make it a valid class name. Ideally it would just start with the migration number but obviously PHP won't allow that! We might end up using Version... as the prefix, although I can't see the problem with using the project name. Is there a specific reason(s) you think it would be a bad idea.

I'll test the Version00001Feature naming convention, I thought I had tried that and it didn't work (but that might have been a few months ago and possibly an older version of the Migrations).

I'll also try out using both folders in dev, I hadn't clocked you could specify multiple folders to search for migrations. What happens if it finds two migrations with the same name? Or does it use the FQ class name?

**Comment by liquorvicar** [comment]
So I've started to look at this.

> If you need dev and prod stuff, it makes more sense to have mutliple migration configuration for  your application.
> The default could be the production one and another migrations configuration could hold everything that's related to the development.
> In that use case you just need to run the migration with the default configuration for production
> And in dev you would just need to also run the migration with both your dev configuration and the default one.

I assumed this meant adding multiple directories to the config for dev like this:
```
doctrine_migrations:
    dir_name:
        - src/Application/Migrations
        - src/Application/Migrations/Dev
    namespace:
        - Application\Migrations
        - Application\Migrations\Dev
    table_name: migration_dev_versions
    name: Application Dev Migrations
```
but that doesn't seem to work. How were you envisaging this set up would work?

**Comment by stof** [comment]
DoctrineMigrationsBundle currently does not allow to have multiple migration configurations in its own config. It exposes a single migration configuration

**Comment by liquorvicar** [comment]
@stof So how would you go about running your migrations with the default configuration and with the dev configuration? Running the console command twice won't work as that would presumably run *all* migrations in the default configuration and then *all* dev migrations afterwards.

**Comment by stof** [comment]
@liquorvicar the point is you cannot have 2 configurations in the bundle configuration. You would have to use doctrine migrations config files (and the ``--configuration`` option of the commands) instead of defining the directories in the symfony config file

**Comment by liquorvicar** [comment]
@stof @mikeSimonson Ok, I've got this (nearly) working how we want out of the box.

config.yml
```
doctrine_migrations:
    dir_name: src/Application/Migrations/Prod
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations
```

config_dev.yml
```
doctrine_migrations:
    dir_name: src/Application/Migrations
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Dev Migrations
```

Our migrations are now called:
- Version001InitialSchema
- Version001InitialSchemaDev
- Version002FirstNewFeature
- VersionFeatureInDev
etc

Everything seems to be working EXCEPT when I migrate up to latest (VersionFeatureInDev), it tells me the next migration is Version001InitialSchema and if I `migrate next` it migrates to Version001InitialSchema by rolling back each migration I have just applied!

Is this a bug in the core migrations code? Shall I post an issue there?

**Comment by mikeSimonson** [comment]
@liquorvicar It's a bug.

What's going on is that doctrine tries do order the migrations and it has expect either a datetime like Version20150804123454BlaBla or Version002AwesomeFeature. It extract the numbers from thoses strings and then order the array of migrations. I don't know exactly what happen when no number is found but the bug is definetly there.

Can you post a bug report and maybe a failing test ?

Thanks

**Comment by mikeSimonson** [comment]
@Aliance There isn't any configuration option for that.
The old finder was kept to make sure that if there was an issue with the new one users could easily go back to the old behavior.

If you want to use the old finder or yours, you need to [instantiate your migration configuration](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Configuration/Configuration.php#L156) and pass the finder to the constructor (It needs to implement the MigrationFinderInterface).

**Comment by goetas** [comment]
implemented in https://github.com/doctrine/DoctrineMigrationsBundle/pull/278

Use: 
```php
$di->setService(...)
```
