### ISSUE TITLE
New tag for consider migrations stable version

### ISSUE THREAD

**Issue by lainosantos** [doctrine/DoctrineMigrationsBundle#129]
https://github.com/doctrine/migrations has tagged its first stable version and many companies projects with minimum-stability to stable can't use this bundle. Please, consider tag a new version based on 1.0.1 (e.g. 1.0.2) with that migrations stable version constraint.

**Comment by mikeSimonson** [comment]
done https://github.com/doctrine/DoctrineMigrationsBundle/commit/ba3d5179b8d37938c58c1e2d8050eff03d362558

Thanks @lainosantos

**Comment by lainosantos** [comment]
@mikeSimonson , I think you don't understand my suggestion. 

Differently of the pulled request #ba3d517 , I suggest create a new tag of this bundle yet, based on last stable tag 1.0.1, for allow projects with minimum stability stable don't need use version constraint dev-master to require stable migrations.

If you create a new branch based on tag 1.0.1, I make a pull request with change, with readme uptades too, for stable migrations.

**Comment by mikeSimonson** [comment]
@lainosantos Sorry I missed it.

**Comment by lainosantos** [comment]
:+1: I will wait the creation of the branch... Thanks.

**Comment by stof** [comment]
@lainosantos the 1.0.1 tag uses a constraint ``~1.0@dev``. The 1.0 release of the library totally matches this constraint anyway

**Comment by lainosantos** [comment]
@stof , I'm sorry. You're right!

@mikeSimonson , Please, close this issue.
