### ISSUE TITLE
Suggestion: an option to ignore migration to execute error

### ISSUE THREAD

**Issue by YanshuoH** [doctrine/DoctrineMigrationsBundle#133]
Hello,

Today, I'm working with Jenkins and DoctrineMigrationsBundle for continuous integration purpose. We decided run the command **doctrine:migration:migrate** for every build in order to keep the database schema up to date (no manual SQL execution of course).

However, this command will raise an exception which comes from *lib/Doctrine/DBAL/Migrations/MigrationException.php* of [doctrine:migrations](https://github.com/doctrine/migrations):

``` 
 [Doctrine\DBAL\Migrations\MigrationException]
  Could not find any migrations to execute.
```

The option**--quiet** does not really bypass the problem because linux code returns always 4 which will be caught by Jenkins

```
echo $?    # results 4
```

Wondering if it's possible to add an option like "--ignore-no-migration-error" or something similar to eventually "try-catch" this exception?

Or do you have any other suggestion for an CI model in database aspect?

**Comment by mikeSimonson** [comment]
@YanshuoH That's an option that should be added into doctrine migrations directly.
Will try to look into it.

**Comment by mikeSimonson** [comment]
Here it is https://github.com/doctrine/migrations/pull/350

**Comment by YanshuoH** [comment]
Thanks a lot!
