### ISSUE TITLE
Custom version numbering scheme?

### ISSUE THREAD

**Issue by patkar** [doctrine/DoctrineMigrationsBundle#134]
In most cases it would be ok, to have the date time as migration version. But I think it would worth it, to support normal incrementing numbers or custom schemes too.

E.g. incrementing numbers (with gaps) would be awesome for github projects, so the migration number can be the number of the pull request or such.

**Comment by mikeSimonson** [comment]
@patkar Normal incrementing numbers are already supported with gaps (datetime have gaps too).

**Comment by patkar** [comment]
:O! So I simply rename auto generated migrations to my numbers :) Didn't know it yet, because I found no documentation. Should I update the docs to mention support for this?

**Comment by mikeSimonson** [comment]
@patkar yes updating the docs would be nice
