### ISSUE TITLE
Revert all migrations back to version 0

### ISSUE THREAD

**Issue by hackzilla** [doctrine/DoctrineMigrationsBundle#135]
```
app/console doctrine:migrations:migrate --env=test 0

                    Application Migrations                    


Unknown version: 0
```

Looking at the doctrine/migrations documentation show  `./doctrine migrations:migrate 0` as an example to revert all migrations.

Link: [Managing Migrations](https://github.com/doctrine/migrations-documentation/blob/master/en/reference/managing_migrations.rst)

**Comment by mikeSimonson** [comment]
@hackzilla That indeed looks like a bug.
Thanks for the report.

**Comment by przemoli** [comment]
I too confirm.
Same output, even though "0" is listed as Previous Version in migrations:status

**Comment by przemoli** [comment]
Workaround:

    app/console doctrine:migrations:execute --down NUMBER_FOR_CURRENT_MIGRATION

**Comment by kgasienica** [comment]
Isn't it still fixed? So there's no way for now to execute revert for all migrations while I dont know versions before?

**Comment by hackzilla** [comment]
```
bin/console doctrine:migrations:migrate 0
                                                              
                    Application Migrations                    
                                                              

Unknown version: 0
```

Using:
            "name": "doctrine/doctrine-migrations-bundle",
            "version": "v1.3.1",

So, yeah, it's still not fixed 3 years later.

**Comment by hackzilla** [comment]
Luckily I don't need it with automation.
I was only testing my migrations worked up and down.

**Comment by blocknotes** [comment]
Any news about this issue?
I have the same problem with the latest version.

**Comment by SenseException** [comment]
The earlier mentioned link to the docs is outdated. Did you try the version aliases? https://www.doctrine-project.org/projects/doctrine-migrations/en/2.1/reference/managing-migrations.html#reverting-migrations

This issue is a mix of migrations and DoctrineMigrationsBundle. It would be nice if this revert-behavior can be tested and then pinned to the right repository/project.

**Comment by blocknotes** [comment]
> The earlier mentioned link to the docs is outdated. Did you try the version aliases? https://www.doctrine-project.org/projects/doctrine-migrations/en/2.1/reference/managing-migrations.html#reverting-migrations

`console doctrine:migrations:migrate first` works, thank you @SenseException

**Comment by SenseException** [comment]
I'm closing this issue because the feature now works with the current implementation. `app/console doctrine:migrations:migrate 0` is outdated.
