### ISSUE TITLE
Doctrine MongoDB ODM compatibility

### ISSUE THREAD

**Issue by sgasser** [doctrine/DoctrineMigrationsBundle#137]
Should this bundle work with Doctrine MongoDB ODM?

In my eyes "Container Aware Migrations" make also sense with ODM.

On 
```
php app/console doctrine:migrations:status
```
or
```
php app/console doctrine:migrations:generate
```
I get following error:
```
You have requested a non-existent service "doctrine". 
```

Approach:
doctrine service name should be configurable.

What do you think?

**Comment by mikeSimonson** [comment]
Right now the issue is that the underlying package does not support the ODM aka (doctrine migrations).
It will be possible in v2 but right now it's completely tight to an sql database.
