### ISSUE TITLE
Manage table "migration_versions" via doctrine:schema:drop / create?

### ISSUE THREAD

**Issue by tackerm** [doctrine/DoctrineMigrationsBundle#148]
I just noticed the following behaviour, which confused me quite a bit. Don't know if this is a bug, by design or just a missing feature:

I'm setting up a new instance of an existing Symfony project. After deploying the code, I run 

`app/console doctrine:schema:create`

to create the database schema. I notice that the table `migration_versions` is not being generated. Now I check the status of my migrations and (obviously) see the following:

```
app/console doctrine:migrations:status

 == Configuration

    >> Name:                                               Recruitment Bundle Migrations
    >> Database Driver:                                    pdo_mysql
    >> Database Name:                                      demo_data
    >> Configuration Source:                               manually configured
    >> Version Table Name:                                 migration_versions
    >> Version Column Name:                                version
    >> Migrations Namespace:                               DemoBundle\Migrations
    >> Migrations Directory:                               /vagrant/demo/app/DoctrineMigrations
    >> Previous Version:                                   Already at first version
    >> Current Version:                                    0
    >> Next Version:                                       2015-07-14 14:00:33 (20150714140033)
    >> Latest Version:                                     2016-02-11 16:43:17 (20160211164317)
    >> Executed Migrations:                                0
    >> Executed Unavailable Migrations:                    0
    >> Available Migrations:                               82
    >> New Migrations:                                     82
```

So the MigrationsBundle now thinks that it has to run all 82 migrations. Because I am using migrations to update a database schema from "old" to "new", the migrations expect an old database schema, which is obviously not the same as the newly created schema. So in other words, all my migrations are broken for this specific instance.

I can of course populate the `migration_versions` table manually with the `doctrine:migrations:version` command (or maybe with a fixture), but wouldn't it make sense to create and populate this table automatically during `doctrine:schema:create`?

Likewise, when running 

`app/console doctrine:schema:drop --force`

I would expect the `migration_versions` table to be removed automatically instead of having to clean things up manually.

**Comment by mikeSimonson** [comment]
The 2 tools have a very different goal.
The ```doctrine:migrations:create``` tool exist to create the schema in the state described by the code whereas the main goal of doctrine migrations is to migrate data. If you have no data to migrate and can just use ```app/console doctrine:schema:create```, you have no use for the migrations.

**Comment by tackerm** [comment]
> The doctrine:migrations:create tool exist to create the schema in the state described by the code

Exactly - the DoctrineMigrationsBundle is installed and configured, so the `migration_versions` table is actually described by the code. That's why I would expect it to be treated as a regular part of the schema.

> the main goal of doctrine migrations is to migrate data

The documentation says something else:

> The database migrations feature is an extension of the database abstraction layer and offers you the ability to programmatically deploy new versions of your database schema

**Comment by mikeSimonson** [comment]
@tackerm The migration_version table is not described by any entity. It's not part of your application ( what I called described by the code ). Proof is when you run ```doctrine:migrations:create``` it can't find any definition for that table ( as there is none).

And for the documentation it definitely need correction.

**Comment by tackerm** [comment]
My point is that the regular procedure to set up a new Symfony instance leaves me with a broken (i.e. non-upgradeable) setup if

1. the DoctrineMigrationsBundle is installed
2. migrations have been added to the project

For me, this is quite a showstopper, and I think it's something that should be addressed.

The documentation is fine - it IS intended for schema updates. See also the docs of the Doctrine Migrations library:

> The Doctrine Migrations offer additional functionality on top of the database abstraction layer (DBAL) for versioning your database schema and easily deploying changes to it

**Comment by mikeSimonson** [comment]
There is absolutely no point at all to use doctrine migrations to version the schema only.
As you said yourself all the data that describe the schema is in the entities already. Thus there is no point trying to duplicate it in a migration file.

The only valid use case for that is when you need to make change to your schema and don't want your user to loose all the data they already have in the previous version of your application. Because ```doctrine:migrations:create``` can only create the database with the last state of the entities and can't guess were to move the data if the schema changed.

If you setup a new instance of your application and it already has 82 migrations you can't use schema:create. If you do because you know there is no data and you want to avoid running all of them to reach the same state, you have to know that we can't guarantee that you will end up with exactly the same schema that if you ran your migrations. Also because you decided not to use the migrations to build your schema well doctrine migrations can't know at which migration you are, so it won't try to guess.

**Comment by tackerm** [comment]
@mikeSimonson I think there has been a misunderstanding - I'm talking about `doctrine:schema:create`, not `doctrine:migrations:create`

**Comment by mikeSimonson** [comment]
@tackerm no it's just me misstyping. I will correct it.

**Comment by tackerm** [comment]
@mikeSimonson Alright :smile: 

So just to make sure I understand this correctly:

As soon as I add a migration, I am no longer supposed to use `doctrine:schema:create` when setting up additional instances? Instead I should write my migrations in a way that they can create the complete schema from scratch at any time?

That would work, but I think it's not really elegant - it would actually force me to duplicate the entire schema definition in the entities AND the migrations...

**Comment by mikeSimonson** [comment]
Yes.
Again this is only usefull if in your migrations you add directives to migrate data, or if you need to add some database vendor specific stuff that can't be described in the entities.
If you don't have data to migrate you can drop all the migrations altogether and use ```schema:create``` to build your database at any point in your development timeline.

**Comment by tackerm** [comment]
@mikeSimonson I just noticed that the `doctrine:migrations:version --add` command has an optional flag `--all`, which tells the bundle to assume that all existing migrations have already been executed.

So running `doctrine:schema:create` followed by `doctrine:migrations:version --add --all` actually solves my issue and makes me happy. A classic case of RTFM - sorry for that! (but thanks for the discussion nevertheless! :smiley: )

**Comment by mikeSimonson** [comment]
Well funny enough I could have swear that I already told you about it but it seems that I forgot to type it.
