### ISSUE TITLE
migrate command ContextErrorException Notice: Undefined offset: 1

### ISSUE THREAD

**Issue by cacahouwete** [doctrine/DoctrineMigrationsBundle#154]
Hi,

It's my first time with this bundle, when I try to install and use it I have the following probleme:

>  bin/console doctrine:migrations:diff
> Generated new migration class to "D:\Projects\proarti2\app/DoctrineMigrations/Version20160311225100.php" from schema differences.
> 
>  bin/console doctrine:migrations:migrate -vvv
> [2016-03-12 00:11:33] event.DEBUG: Notified event "console.command" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".
> [2016-03-12 00:11:33] event.DEBUG: Notified event "console.command" to listener "Symfony\Bridge\Monolog\Handler\ConsoleHandler::onCommand".
> [2016-03-12 00:11:33] event.DEBUG: Notified event "console.command" to listener "Symfony\Bridge\Monolog\Handler\ConsoleHandler::onCommand".
> 
> ```
>                 Application Migrations
> ```
> 
> [2016-03-12 00:11:34] doctrine.DEBUG: SELECT quote_ident(table_name) AS table_name,                        table_schema AS schema_name                 FROM   information_schema.tables                 WHERE  table_schema NOT LIKE 'pg_%'                 AND    table_schema != 'information_schema'                 AND    table_name != 'geometry_columns'                 AND    table_name != 'spatial_ref_sys'                 AND    table_type != 'VIEW'
> [2016-03-12 00:11:34] doctrine.DEBUG: SELECT nspname as schema_name FROM pg_namespace WHERE nspname !~ '^pg_.*' and nspname != 'information_schema'
> [2016-03-12 00:11:34] doctrine.DEBUG: SHOW search_path
> [2016-03-12 00:11:34] doctrine.DEBUG: SELECT version FROM migration_versions
> WARNING! You are about to execute a database migration that could result in schema changes and data lost. Are you sure you wish to continue? (y/n)y
> [2016-03-12 00:11:36] doctrine.DEBUG: SELECT version FROM migration_versions WHERE version IN ('20160311225100') ORDER BY version DESC LIMIT 1
> [2016-03-12 00:11:36] doctrine.DEBUG: SELECT version FROM migration_versions
> Migrating up to 20160311225100 from 0
> [2016-03-12 00:11:36] doctrine.DEBUG: "START TRANSACTION"
> Migration 20160311225100 failed during Pre-Checks. Error Notice: Undefined offset: 1
> [2016-03-12 00:11:36] doctrine.DEBUG: "ROLLBACK"
> 
>   [Symfony\Component\Debug\Exception\ContextErrorException]
>   Notice: Undefined offset: 1
> 
> Exception trace:
>  () at D:\Projects\proarti2\vendor\zendframework\zend-code\src\Generator\MethodGenerator.php:98
>  Symfony\Component\Debug\ErrorHandler->handleError() at D:\Projects\proarti2\vendor\zendframework\zend-code\src\Generator\MethodGenerator.php:98
>  Zend\Code\Generator\MethodGenerator::clearBodyIndention() at D:\Projects\proarti2\vendor\zendframework\zend-code\src\Generator\MethodGenerator.php:77
>  Zend\Code\Generator\MethodGenerator::fromReflection() at D:\Projects\proarti2\vendor\ocramius\proxy-manager\src\ProxyManager\Generator\MethodGenerator.php:39
>  ProxyManager\Generator\MethodGenerator::fromReflection() at D:\Projects\proarti2\vendor\ocramius\proxy-manager\src\ProxyManager\ProxyGenerator\LazyLoadingValueHolder\MethodGenerator\LazyLoadingMethodInterceptor.php:48
>  ProxyManager\ProxyGenerator\LazyLoadingValueHolder\MethodGenerator\LazyLoadingMethodInterceptor::generateMethod() at D:\Projects\proarti2\vendor\ocramius\proxy-manager\src\ProxyManager\ProxyGenerator\LazyLoadingValueHolderGenerator.php:118
>  ProxyManager\ProxyGenerator\LazyLoadingValueHolderGenerator->ProxyManager\ProxyGenerator{closure}() at n/a:n/a
>  array_map() at D:\Projects\proarti2\vendor\ocramius\proxy-manager\src\ProxyManager\ProxyGenerator\LazyLoadingValueHolderGenerator.php:90
>  ProxyManager\ProxyGenerator\LazyLoadingValueHolderGenerator->generate() at D:\Projects\proarti2\vendor\ocramius\proxy-manager\src\ProxyManager\Factory\AbstractBaseFactory.php:119
>  ProxyManager\Factory\AbstractBaseFactory->generateProxyClass() at D:\Projects\proarti2\vendor\ocramius\proxy-manager\src\ProxyManager\Factory\AbstractBaseFactory.php:82
>  ProxyManager\Factory\AbstractBaseFactory->generateProxy() at D:\Projects\proarti2\vendor\ocramius\proxy-manager\src\ProxyManager\Factory\LazyLoadingValueHolderFactory.php:45
>  ProxyManager\Factory\LazyLoadingValueHolderFactory->createProxy() at D:\Projects\proarti2\vendor\doctrine\migrations\lib\Doctrine\DBAL\Migrations\Provider\LazySchemaDiffProvider.php:66
>  Doctrine\DBAL\Migrations\Provider\LazySchemaDiffProvider->createFromSchema() at D:\Projects\proarti2\vendor\doctrine\migrations\lib\Doctrine\DBAL\Migrations\Version.php:277
>  Doctrine\DBAL\Migrations\Version->execute() at D:\Projects\proarti2\vendor\doctrine\migrations\lib\Doctrine\DBAL\Migrations\Migration.php:176
>  Doctrine\DBAL\Migrations\Migration->migrate() at D:\Projects\proarti2\vendor\doctrine\migrations\lib\Doctrine\DBAL\Migrations\Tools\Console\Command\MigrateCommand.php:143
>  Doctrine\DBAL\Migrations\Tools\Console\Command\MigrateCommand->execute() at D:\Projects\proarti2\vendor\doctrine\doctrine-migrations-bundle\Command\MigrationsMigrateDoctrineCommand.php:54
>  Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute() at D:\Projects\proarti2\vendor\symfony\symfony\src\Symfony\Component\Console\Command\Command.php:259
>  Symfony\Component\Console\Command\Command->run() at D:\Projects\proarti2\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:860
>  Symfony\Component\Console\Application->doRunCommand() at D:\Projects\proarti2\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:192
>  Symfony\Component\Console\Application->doRun() at D:\Projects\proarti2\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php:92
>  Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at D:\Projects\proarti2\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:123
>  Symfony\Component\Console\Application->run() at D:\Projects\proarti2\bin\console:29
> 
> doctrine:migrations:migrate [--write-sql] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--db DB] [--em EM] [--shard SHARD] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command> [<version>]

My config:
Symfony2.8.3
PHP7.0.4

composer require :+1:

```

    "symfony/symfony": "^2.8",
    "doctrine/orm": "^2.5",
    "doctrine/doctrine-bundle": "^1.6",
    "doctrine/doctrine-migrations-bundle": "^1.1",
    "symfony/swiftmailer-bundle": "^2.3",
    "symfony/monolog-bundle": "^2.8",
    "symfony/assetic-bundle": "^2",
    "sensio/distribution-bundle": "~5.0",
    "sensio/framework-extra-bundle": "^3.0.2",
    "incenteev/composer-parameter-handler": "^2.0",
```

I've done something wrong ?

**Comment by mikeSimonson** [comment]
Can you show the result of running ``doctrine/migrations show -i | grep ocramius`` and ``doctrine/migrations show -i | grep migrations`` ?

Thanks for the report @cacahouete78

**Comment by cacahouete78** [comment]
ocramius/package-versions 1.0.3
ocramius/proxy-manager 2.0.1
doctrine/doctrine-migrations-bundle 1.1.1
doctrine/migrations v1.4.0

**Comment by mikeSimonson** [comment]
I will try to reproduce it.

**Comment by cacahouete78** [comment]
I don t know if it's important but I'm on windows 10 and I use postgresql9.5 or mysql5.7 depending to my projects.
I tried to use the bundle by creating new blank project under sumfony2 and 3, but the problem persists.

**Comment by mikeSimonson** [comment]
How did you created those blank projects ?

**Comment by cacahouete78** [comment]
with symfony installer (http://symfony.com/download) :
symfony new symfony3 3.0
symfony new symfony2 2.8
(in composer.json of symfony2.8 project I deleted these lines :
 "platform": {
            "php": "5.3.9"
        }
)

**Comment by mikeSimonson** [comment]
Okay, can you paste the content of the "D:\Projects\proarti2\app/DoctrineMigrations/Version20160311225100.php" migration file ?

Is it the first migration file that was created ?

**Comment by cacahouete78** [comment]
I deleted the file but I can paste the test content Symfony2 / 3 that I did to reproduce the error.

Symfony2:
```
<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20160312142047 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE testiii (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, extra LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('DROP TABLE testiii');
    }
}
```

Symfony3:

```
<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20160312140337 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE testi (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, extra LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('DROP TABLE testi');
    }
}
```

**Comment by mikeSimonson** [comment]
@cacahouete78 I am sorry, but I am unable to reproduce the bug.

Are you able to ?

**Comment by cacahouete78** [comment]
In which environment did you try to reproduce?

Have you tried to reproduce the bug on windows 10? with the version of php ["Thread Safe php7.0.4 VC14 x64"] (http://windows.php.net/download/)

**Comment by mikeSimonson** [comment]
no in a vagrant linux php 7.0.5-dev.

Could you run the same code on linux in a virtualbox to check if the issue is platform specific ?

**Comment by cacahouete78** [comment]
With exactly the same procedure (Create blank symfony project and install the bundle) when I try to migrate it WORKS ! The problem is due to the environment, but I don t know where and why ^^,

**Comment by mikeSimonson** [comment]
Is eval disabled in your windows configuration ?
Are you sure that the problem still happen if you start from a blank project on windows ?

Can you try to use xdebug or pshysh to find out what's going on ?

**Comment by mikeSimonson** [comment]
Do you have the reflection extension on windows ?

**Comment by mikeSimonson** [comment]
It looks like the call to ``$reflectionMethod->getBody()`` at 
https://github.com/zendframework/zend-code/blob/master/src/Generator/MethodGenerator.php#L77
return an empty array on windows.

If you could confirm that with xdebug, that would be great.

**Comment by cacahouete78** [comment]
Yes eval is disabled, yes it s only on windows the probleme is ^^,
Yes I have xdebug , but i don t know how to use it correctly :s

because i m a bite noob i modified these lines to make some test :

```
        $tmp = $reflectionMethod->getBody();
        var_dump('first dump');
        var_dump($tmp);
        var_dump('second dump');
        var_dump(static::clearBodyIndention($tmp));
        var_dump('end dump');
        $method->setBody(static::clearBodyIndention($tmp));
```

Return value:
```
WARNING! You are about to execute a database migration that could result in schema changes and data lost. Are you sure you wish to continue? (y/n)y
Migrating up to 20160312142047 from 0
D:\Projects\symfony2\vendor\zendframework\zend-code\src\Generator\MethodGenerator.php:78:
string(10) "first dump"
D:\Projects\symfony2\vendor\zendframework\zend-code\src\Generator\MethodGenerator.php:79:
string(69) "
        return $this->_schemaConfig->hasExplicitForeignKeyIndexes();"
D:\Projects\symfony2\vendor\zendframework\zend-code\src\Generator\MethodGenerator.php:80:
string(11) "second dump"
Migration 20160312142047 failed during Pre-Checks. Error Notice: Undefined offset: 1

                                                             
  [Symfony\Component\Debug\Exception\ContextErrorException]  
  Notice: Undefined offset: 1          
```

**Comment by mikeSimonson** [comment]
Go at lines https://github.com/zendframework/zend-code/blob/master/src/Generator/MethodGenerator.php#L96 and var_dump the $lines variable.

**Comment by cacahouete78** [comment]
D:\Projects\symfony2\vendor\zendframework\zend-code\src\Generator\MethodGenerator.php:97:
array(1) {
  [0] =>
  string(69) "
        return $this->_schemaConfig->hasExplicitForeignKeyIndexes();"
}

**Comment by mikeSimonson** [comment]
I think that the bug is at this line https://github.com/zendframework/zend-code/blob/master/src/Generator/MethodGenerator.php#L96
Because on windows the line ending is '\r\n' the explode call only return one line and thus the next line fail.
If you replace the PHP_EOL with "\n" it will works, I think.

Thanks for the effort and the bug report.

**Comment by cacahouete78** [comment]
I replaced PHP_EOL with "\n" and the probleme persist , he don t know explode :s

**Comment by mikeSimonson** [comment]
What do you mean by he don't know explode ?

**Comment by mikeSimonson** [comment]
Did you use single quote or double quote around the \n ?

**Comment by cacahouete78** [comment]
sorry I put single quote :s , it works :

        $lines = explode("\n", $body);

**Comment by cacahouete78** [comment]
you know if it will fix soon ?

**Comment by mikeSimonson** [comment]
I posting an issue right now. I will keep this issue open until it's fixed.

**Comment by Richard87** [comment]
Fore your information (whenever you're back from vacation ;) )

Changing MethodReflection:231 from "\n" to PHP_EOL solved the issue on my first test, no idea what kind of side effects this will have though :P

Also, all my files all my files are CRLF, files I have created myself, and created with symfony's `generate:controller/command`  etc

When doing `doctrine:migrate:generate/diff` it creates files where line endings are always LF

**Comment by steve-todorov** [comment]
I can confirm replacing `PHP_EOL` with `"\n"` in `Zend\Code\Reflection\MethodReflection\MethodGenerator` solves the problem.

**Comment by sasclar** [comment]
PHP_EOL replacement by "\n" in Zend\Code\Reflection\MethodReflection\MethodGenerator solved the problem for me too on win7x64
