### ISSUE TITLE
[Info] update bundle dependecy

### ISSUE THREAD

**Issue by noniagriconomie** [doctrine/DoctrineMigrationsBundle#155]
hi

i would like to have this option https://github.com/doctrine/migrations/issues/445 (--allow-no-migration)

Is it possible for you to update the bundle?

thanks

**Comment by mikeSimonson** [comment]
you just need to composer update and it will be available.

**Comment by noniagriconomie** [comment]
I tried it and no, that is why i opened this issue

**Comment by mikeSimonson** [comment]
How did you tried to update it ?

**Comment by noniagriconomie** [comment]
update the bundle with composer as usual, maybe a dependecy that conflict with it

I will investigate, do not bother with that if you are sure that an update will add the feature

Anyway thanks @mikeSimonson
