### ISSUE TITLE
Delete version from database also if file does not exist

### ISSUE THREAD

**Issue by JHGitty** [doctrine/DoctrineMigrationsBundle#166]
I want to remove a version from the database also if the migration file does not exist. This is currently not possible. `php bin/console doctrine:migration:version XXX --delete` will result into an error if the migration file does not exist.

I think we should do an interaction question in this case to ask if the version should really be removed from the database.

**Comment by brizzz** [comment]
Have the same issue. I also want to add migrations version via `doctrine:migration:version XXX --add`, even if the file does not exist.

**Comment by JHGitty** [comment]
You could just add a dummy file to delete it - but this bug should really be fixed.

**Comment by LuigiCardamone** [comment]
This is a big problem when you switch among branches with different migrations. Any updates?

**Comment by jwage** [comment]
I haven't seen anyone contribute this yet.

**Comment by LuigiCardamone** [comment]
On my project I created a script to clear all missing migrations:

`php bin/console doctrine:migrations:migrate --no-interaction --env=${ENV}`
`php bin/console doctrine:query:sql "TRUNCATE migration_versions" --env=${ENV}`
`php bin/console doctrine:migrations:version --add --all --no-interaction --env=${ENV}`

It is not a clean solution, but it is the only one that I found so far. I use this script when I switch to a branch in which some migration files are missing.

**Comment by jschaedl** [comment]
https://github.com/doctrine/migrations/issues/795

**Comment by jwage** [comment]
This will be fixed with #795
