### ISSUE TITLE
MongoDB compatibility

### ISSUE THREAD

**Issue by murilolobato** [doctrine/DoctrineMigrationsBundle#170]
As I can see, there is no support for ODM. But, what if I don't want use 'diff' ? Can I create a Container Aware migration, and write my MongoDB commands manually? Is this OK? Or I will have problems?

PS.: My application, will also use doctrine migrations to manage a postgresql schema. Normal, usage.

**Comment by mikeSimonson** [comment]
Right now you will have issue as the logic that update the state of a migration contains sql queries.
In the current form it's not possible to support the ODM. It will be supported in the next version.

**Comment by murilolobato** [comment]
Ok, I think i understood that. But, my application has an postgresql database that will receive migrations, and occasionaly I want to execute some mongodb migrations. What about the following code? Will it bring problems? Beacuse in my tests it works fine.

```php
/**
 *
 */
class Version20160509213111 extends AbstractMigration implements ContainerAwareInterface
{
    /**
     * @var ContainerInterface
     */
    private $container;

    public function setContainer(ContainerInterface $container = null)
    {
        $this->container = $container;
    }

    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        $dm = $this->container->get('doctrine_mongodb');

        /** @var Builder $qb */
        $qb = $dm->getRepository("AppBundle:Foo")->createQueryBuilder();

        // This will create the property bar on all Foo documents. 
        $qb
            ->update()
            ->multiple(true)
            ->field('bar')->set('Hello')->exists(false)
            ->getQuery()
            ->execute()
        ;
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // The appropriate down function
    }
}
```

**Comment by stof** [comment]
@murilolobato IMO, applying migrations in mongo should be handled separately from your postgresql migrations (your code will still use the postgresql db to store whether the mongo database was migrated or no, which looks weird).

and there is already 2 ways to create migrations:
- ``diff`` will compare schemas and generate the appropriate SQL queries
- ``generate`` will just generate an empty migration

**Comment by mikeSimonson** [comment]
@murilolobato You won't have any issue doing that (afaik) but as @stof said I think that it would make more sense to have 2 migrations configurations. One for your postgres database and one for mongodb that could store the state of the mongodb migrations in sqlite maybe ?

**Comment by murilolobato** [comment]
Alright then. I'm just trying to find a way to manage this case of mongodb migration. I knew that `diff`command would not work for mongodb, and console output would not be precise in these cases, because it would not track mongodb 'queries', but none of those would be a problem. My intention is just to keep track of migrations, storing them into VCS with DoctrineMigrations, and be able to reproduce  a previous state of my application.

For now, I can't find other way to manage mongodb migrations, and I'm open to suggestions. And for my scenario, an mongodb migration is in most cases prefixed by a postgresql migration.

**Comment by mikeSimonson** [comment]
Then maybe it makes sense to have the mongodb migration in the same file as the postgres if they are related.

**Comment by murilolobato** [comment]
Thank for all you support, it was very important. All our talk make me to pay attention to all details. Hope for one day DoctrineMigrations supports officially mongodb. Thank all you!!
