### ISSUE TITLE
release new version please

### ISSUE THREAD

**Issue by hjanuschka** [doctrine/DoctrineMigrationsBundle#172]
to update the following - can you do a github release?
 - zendframework/zend-code (2.6.3) latest is 3.0.2

  - ocramius/proxy-manager (1.0.2) latest is 2.0.2

**Comment by stof** [comment]
doctrine/migrations is compatible with both ocramius/proxy-manager 1.x and 2.x in the latest release.
The version installed by composer depends on your PHP version (ocramius/proxy-manager 2.x requires PHP 7+)
