### ISSUE TITLE
Execute migrations before diff command

### ISSUE THREAD

**Issue by gtrias** [doctrine/DoctrineMigrationsBundle#177]
I think It could be nice if `doctrine:migrations:migrate` will be executed automatically before `doctrine:migrations:diff` in order to not generate incorrect diff due the current database is not sync with already created migrations. 
Or at least show a warning advising that the current database is not in sync with the migrations.
It aims to help to avoid migrations issues when developing specially in continous deployment scenarios.

**Comment by mikeSimonson** [comment]
@gtrias The diff command is only a dev command so it won't run the migrate command automatically.
But a PR with a warning not in sync with the current migrations is welcome.

**Comment by gtrias** [comment]
Well, I understand that `diff` is a dev command but it makes no sense to run it if you are not in sync because it will generate an incorrect migration file that will break in production. I don't see what has to do the fact is a dev command to not run the `migrate` command, all in all is what I do before each time I has to generate a new migration file.

I'll try to make the PR anyway.

**Comment by mikeSimonson** [comment]
The reason is that this tool shouldn't try to be more clever than it's user.
It's a good idea to show a warning message but it's a very bad idea to do something automatically behind the back of the user. Because it would work most of the time for your use case doesn't make it a good behaviour in the general use case.

**Comment by garex** [comment]
Another possible behavior: just dont' allow to run `diff` if there are not-synced migrations.

But what if I created migration1 with filter command and want to create migration2 with another filter command? Then this behaviour would be bad.

**Comment by fesor** [comment]
Shouldn't this be addressed to doctrine/migrations package?

**Comment by stof** [comment]
it should

**Comment by VincentLanglet** [comment]
@goetas I think you can close this issue too.

**Comment by goetas** [comment]
solved in https://github.com/doctrine/migrations/pull/948
