### ISSUE TITLE
DoctrineMigrationsBundle - "configuration" option is overwriten by DoctrineCommand::configureMigrations()

### ISSUE THREAD

**Issue by zulus** [doctrine/DoctrineMigrationsBundle#18]
In my project I have many connections (central, acl[another issue], dynamic based on company table - fake connection and ConnectionFactory ;] ).

I have to migrate the database independently of each other, but "DoctrineCommand:: configureMigrations" always overwrite - path configuration option :(

**Comment by jrobeson** [comment]
did the fix in https://github.com/doctrine/DoctrineMigrationsBundle/issues/95 work ?

**Comment by jrobeson** [comment]
@mikeSimonson : can this be closed to then?

**Comment by stof** [comment]
Closing because it is fixed in the library with https://github.com/doctrine/migrations/pull/219
