### ISSUE TITLE
The parameter "doctrine_migrations.organize_migrations" must be defined.

### ISSUE THREAD

**Issue by n-sviridenko** [doctrine/DoctrineMigrationsBundle#180]
After 1.2 I have an Exception "The parameter "doctrine_migrations.organize_migrations" must be defined."
I think that you need to add it to breaking changes, because with 1.1 I didn't need to type a configuration.

**Comment by mikeSimonson** [comment]
@n-sviridenko What kind of configuration did you use ?

**Comment by n-sviridenko** [comment]
@mikeSimonson YAML, but I didn't fill it.

**Comment by goetas** [comment]
Not a problem since https://github.com/doctrine/DoctrineMigrationsBundle/pull/278
