### ISSUE TITLE
Feature request: allow doctrine:migrations:migrate up/down

### ISSUE THREAD

**Issue by verheyenkoen** [doctrine/DoctrineMigrationsBundle#182]
Allow the `migrate` command to be used like this: `doctrine:migrations:migrate up` and `doctrine:migrations:migrate down`, which will result in a one step forward or backward migration.

Alternatively this could also be `doctrine:migrations:step up` and `doctrine:migrations:step down`.

**Comment by mikeSimonson** [comment]
That's an interesting idea.

@verheyenkoen Are you willing to work on it ?

**Comment by verheyenkoen** [comment]
Ok, silly me, apparently this already exists, but it's called `prev`and `next`. `first` and `latest` (default) also exist btw.
