### ISSUE TITLE
[Feature] Custom warning prompt

### ISSUE THREAD

**Issue by martixy** [doctrine/DoctrineMigrationsBundle#185]
I have simple suggestion: Allow custom messages in the interactive warning prompt.

The migrations project allows adding warnings, but they are not interactive.
Having a custom interactive warning would be quite useful in scenarios where you need to provide critical information to the person executing the migration _before_ it starts.

**Comment by mikeSimonson** [comment]
What do you mean by interactive ?
Custom message would be nice anyway.

**Comment by martixy** [comment]
Interactive as in "can take actions". Like saying "no". :)
The same `askConfirmation` prompt that already happens except with custom messages you can set in the  migration.

**Comment by goetas** [comment]
Running migrations is meant to be a fully automated process (eventually done in a via Continuous Integration environment), thus without interaction with the user. Because of this, I consider this feature request out of scope for this library.
