### ISSUE TITLE
Update documentation Symfony's website

### ISSUE THREAD

**Issue by sekjun9878** [doctrine/DoctrineMigrationsBundle#186]
The documentation on this page is outdated:

http://symfony.com/doc/current/bundles/DoctrineMigrationsBundle/index.html

For example, executables are now located at bin/console not app/console.

**Comment by mikeSimonson** [comment]
@sekjun9878 It depends what version of symfony you install

**Comment by sekjun9878** [comment]
@mikeSimonson I was talking about the latest version, 3.1. Hopefully that is supported?

**Comment by mikeSimonson** [comment]
It is supported but if you use an older version of symfony the executable won't be located in the bin folder.

**Comment by sekjun9878** [comment]
@mikeSimonson There's a version dropdown on the documentation page so you can have multiple versions of docs for different versions (I don't know how that works), but it's ultimately upto you.

**Comment by xabbuh** [comment]
@sekjun9878 The thing is that the location of the `console` script is not depending on the bundle's version (which the version switcher is about), but depends on the version of the Symfony Standard Edition.

**Comment by sekjun9878** [comment]
@xabbuh I see. I just wanted to make this issue aware - you can either keep it open as a reminder or close the issue, I don't mind. Thanks for maintaining this bundle!

**Comment by fabpot** [comment]
Closing as there is nothing we can do.
