### ISSUE TITLE
[Feature] Default connection configuration option for performing migration commands

### ISSUE THREAD

**Issue by scaytrase** [doctrine/DoctrineMigrationsBundle#189]
Use case:

We have two separate connections - one for general doctrine flow and one with administer permissions to perform migrations and schema maintenance. In order to perform migrations all our CI jobs and manual commands should be provided with `--db=migrations` command-line option.

It would be much easier if we can have a confiig option like

```yml
doctrine_migrations:
    connection: migrations
```

to skip this options for further calls

**Comment by mikeSimonson** [comment]
You can use the migrations-db.php file were you could store the connection parameter as a quick fix.

Otherwise the PR is welcome.

**Comment by scaytrase** [comment]
I've can override command itself as well, but it is not shareable option :)

I hope I'll get some time to implement it.

**Comment by pyatnitsev** [comment]
#264 Related PR

**Comment by goetas** [comment]
implemented in https://github.com/doctrine/DoctrineMigrationsBundle/pull/278
