### ISSUE TITLE
Remove the "name" config option

### ISSUE THREAD

**Issue by javiereguiluz** [doctrine/DoctrineMigrationsBundle#194]
About the `name` config, @stof [commented this](https://github.com/symfony/recipes/pull/57#discussion_r115993936):

> I would remove this config:
>
> the table name you provide here is just repeating the default value, which is fine for most people. So just rely on the default value instead. Adding the config explicitly in projects makes sense only if people are expected to modify it
>
> the name is almost useless. It is used only for display purposes (and as the bundle does not support having several migration configurations in parallel, using a meaningful name for the migration config does not bring much)

So, if you agree, can someone please submit a pull request to deprecate/remove that option? Thanks!

**Comment by stof** [comment]
@javiereguiluz my comment on the recipe was not really about removing the feature from the bundle itself (even though it may still make sense), but to remove it from the config file created by the recipe (as configuring the name explicitly in the project does not make sense for 99.9% of people at least)

**Comment by javiereguiluz** [comment]
Closing because as @stof said, setting this explicitly is not relevant for most developers. Thanks!
