### ISSUE TITLE
Migrations on multiple servers at the same time?

### ISSUE THREAD

**Issue by pdolinaj** [doctrine/DoctrineMigrationsBundle#196]
This is not a bug but rather question / feature request.

Is it possible to run the migrations on multiple servers at the same time without running the same scripts multiple times?

The problem I am having is that we are using multiple servers and they run the migrations every time we deploy a new version of our APP. This causes that the same migration scripts being run several times (depending on how many servers are running it).

Is there a way to check whether the migration is in progress and if yes, skip it or this is something I would need to implement manually?

Many thanks.

**Comment by mikeSimonson** [comment]
Hi,

You will need to implement that manually yourself.

Cheers
