### ISSUE TITLE
undefined method  Configuration::getCustomTemplate()  

### ISSUE THREAD

**Issue by jewome62** [doctrine/DoctrineMigrationsBundle#207]
Hello,

I install doctrine migrations bundle, in this instant.
But i have error when i try make doctrine:migrations:diff

```
# bin/console d:m:d
                                                                                                      
  [Symfony\Component\Debug\Exception\FatalThrowableError]                                             
  Call to undefined method Doctrine\DBAL\Migrations\Configuration\Configuration::getCustomTemplate()  
# composer show -i doctrine/doctrine-migrations-bundle
Do not run Composer as root/super user! See https://getcomposer.org/root for details
You are using the deprecated option "installed". Only installed packages are shown by default now. The --all option can be used to show all packages.
name     : doctrine/doctrine-migrations-bundle
descrip. : Symfony DoctrineMigrationsBundle
keywords : dbal, migrations, schema
versions : * dev-master, 1.2.x-dev
type     : symfony-bundle
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/doctrine/DoctrineMigrationsBundle.git 582f503e1f92236da4772c58e53ac06aab534f96
dist     : [zip] https://api.github.com/repos/doctrine/DoctrineMigrationsBundle/zipball/582f503e1f92236da4772c58e53ac06aab534f96 582f503e1f92236da4772c58e53ac06aab534f96
names    : doctrine/doctrine-migrations-bundle

autoload
psr-4
Doctrine\Bundle\MigrationsBundle\ => .

requires
doctrine/doctrine-bundle ~1.0
doctrine/migrations ^1.1
php >=5.4.0
symfony/framework-bundle ~2.3|~3.0

requires (dev)
phpunit/phpunit ~4.8
```

I try last stable version and dev-master

**Comment by gondo** [comment]
same here, master is broken, you have to use:
`"doctrine/doctrine-migrations-bundle": "1.2.1",`

**Comment by thatside-zaraffa** [comment]
Same here. 
Seems it would be fixed soon: https://github.com/doctrine/migrations/pull/545

**Comment by lcobucci** [comment]
@thatside-zaraffa doctrine/migrations#545 is actually a different thing and it's related to #206. `Configuration#getCustomTemplate()` is only available on `doctrine/migrations: v1.6.x-dev` so the bundle should only call that method when that specific version is installed.

**Comment by mmucklo** [comment]
Seems like it was caused by this merging PR#200 into master.

https://github.com/doctrine/DoctrineMigrationsBundle/commit/582f503e1f92236da4772c58e53ac06aab534f96

**Comment by lcobucci** [comment]
Exactly, what needs to be done is checking if the method is available (maybe with `package_version`?) before of calling it. Maybe even alerting the user when it tries to configure a custom template but doesn't have the correct version installed.

**Comment by PeterLabos** [comment]
To avoid this bug, just add dependency in your composer.json to request  "doctrine/migrations": "dev-master", but that requires php7.1.

@lcobucci Another way, is to run method_exist() before calling method of external class. But that can create a problem with custom template not working without knowing what is wrong. Which leads to more complex solution handling errors.

**Comment by smcjones** [comment]
This is a composer.json issue. It would easily be resolved if this package's v1.3.*+ version required doctrine/migrations 1.6+ or dev-master to operate.

**Comment by ruudvanderweijde** [comment]
Version 1.3 now breaks because of:
```
  [Symfony\Component\Debug\Exception\UndefinedMethodException]
  Attempted to call an undefined method named "getCustomTemplate" of class "Doctrine\DBAL\Migrations\Configuration\Configuration".
```
This release version is quite useless.

**Comment by lcobucci** [comment]
@ruudvanderweijde please do send a PR with your suggestion to fix the problem and create a useful release

**Comment by lcobucci** [comment]
[v1.3.1](https://github.com/doctrine/DoctrineMigrationsBundle/releases/tag/v1.3.1) released please upgrade.
