### ISSUE TITLE
addSql --write-sql Prepare statement

### ISSUE THREAD

**Issue by prodevcon** [doctrine/DoctrineMigrationsBundle#209]
Hi,

Is it normal that I don't see real values when I check the SQL from a generated file
```sql
UPDATE user SET happy = true WHERE name = :name AND id = :id;
UPDATE user SET happy = true WHERE name = :name AND id = :id;
UPDATE user SET happy = true WHERE name = :name AND id = :id;
```
I used the example from documentation: http://docs.doctrine-project.org/projects/doctrine-migrations/en/latest/reference/migration_classes.html

```php
$users = array(
    array('name' => 'mike', 'id' => 1),
    array('name' => 'jwage', 'id' => 2),
    array('name' => 'ocramius', 'id' => 3),
);
foreach ($users as $user) {
    $this->addSql('UPDATE user SET happy = true WHERE name = :name AND id = :id', $user);
}
`
Or docs are wrong?
Thx

**Comment by stof** [comment]
I don't think `--write-sql` works well when you have prepared statements, as there is no way to prepare the statements (as statements are not sent to the DB at all).

**Comment by prodevcon** [comment]
Ok, thx.
that explains it

**Comment by prodevcon** [comment]
Hi @stof 

when I use --write-sql with migration, I see real values in console output:
```sh
     -> INSERT INTO dc_rules_companies (url_collector_rule_id, company_id) VALUES ( :url_collector_rule_id, :company_id ) with parameters (:url_collector_rule_id => 20, :company_id => 1313)
     -> INSERT INTO dc_rules_companies (url_collector_rule_id, company_id) VALUES ( :url_collector_rule_id, :company_id ) with parameters (:url_collector_rule_id => 20, :company_id => 1314)
     -> INSERT INTO dc_rules_companies (url_collector_rule_id, company_id) VALUES ( :url_collector_rule_id, :company_id ) with parameters (:url_collector_rule_id => 20, :company_id => 1315)
     -> INSERT INTO dc_rules_companies (url_collector_rule_id, company_id) VALUES ( :url_collector_rule_id, :company_id ) with parameters (:url_collector_rule_id => 20, :company_id => 1316)

  ++ migrated (0.77s)
```

but in the generated SQL file (ex. 'doctrine_migration_20171006120410.sql') I see placeholders and not real values:
```sql
INSERT INTO dc_rules_companies (url_collector_rule_id, company_id) VALUES ( :url_collector_rule_id, :company_id );
INSERT INTO dc_rules_companies (url_collector_rule_id, company_id) VALUES ( :url_collector_rule_id, :company_id );
INSERT INTO dc_rules_companies (url_collector_rule_id, company_id) VALUES ( :url_collector_rule_id, :company_id );
INSERT INTO migration_versions (version) VALUES ('20171005125441');
```

**Comment by stof** [comment]
Well, the console output displays the SQL query, and then the parameters after that. But this does not mean that the full console output is valid SQL.

When being asked to write the SQL file, the only way I can think of to provide the parameters would be to put a comment.

DBAL will **NEVER** replace placeholders with actual values itself. This would not be a prepared statement anymore (it would be equivalent with you doing string concatenation)

**Comment by prodevcon** [comment]
Great! @stof Thank you for your explanation!
