### ISSUE TITLE
PHP 7.x tests are faling

### ISSUE THREAD

**Issue by gabriel-caruso** [doctrine/DoctrineMigrationsBundle#219]
Discovered in #218, [all `PHP 7.x` tests](https://travis-ci.org/doctrine/DoctrineMigrationsBundle/builds/307170286) are falling because of an [`doctrine/migrations` method declare with PHP 7 return type `?string`](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Configuration/Configuration.php#L363). How can we solve it? :thinking:

**Comment by alcaeus** [comment]
See https://github.com/doctrine/DoctrineMigrationsBundle/pull/220#issuecomment-347765779.
