### ISSUE TITLE
Doctrine Migrations causing Doctrine Entity Listener service error

### ISSUE THREAD

**Issue by heather817** [doctrine/DoctrineMigrationsBundle#225]
I have the following versions:

```
doctrine/annotations                 v1.4.0  
doctrine/cache                       v1.6.2  
doctrine/collections                 v1.4.0  
doctrine/common                      v2.7.3  
doctrine/dbal                        v2.5.13 
doctrine/doctrine-bundle             1.9.1   
doctrine/doctrine-cache-bundle       1.3.3   
doctrine/doctrine-migrations-bundle  v1.3.1  
doctrine/inflector                   v1.1.0  
doctrine/instantiator                1.0.5   
doctrine/lexer                       v1.0.1  
doctrine/migrations                  v1.5.0  
doctrine/orm                         v2.5.14 

symfony/symfony                      v3.4.9  
```

I have an entity listener set up according to the service definition at https://symfony.com/doc/master/bundles/DoctrineBundle/entity-listeners.html

It has a service argument for taking the service container (arguments: ["@service_container"]), which is then handled by the symfony dependency injection.

All this was working before I installed the doctrine migrations, then after installing, when flushing I get an error like this:

`Catchable Fatal Error: Argument 1 passed to Core\DataFormsBundle\EntityListener\DataFormListener::__construct() must implement interface Psr\Container\ContainerInterface, none given, called in ...\vendor\doctrine\doctrine-bundle\Mapping\ContainerAwareEntityListenerResolver.php on line 76 and defined`

Then un-installing doctrine migrations bundle removes the error and the listener works as expected.

Has anyone else had an error like this?

**Comment by PReimers** [comment]
@heather817 is this issue still occuring after upgrading to the latest versions?

**Comment by pnnl-coral** [comment]
I don't know, I could spend some time with old code, but we moved on to Symfony 4 and have not had any issues with any versions of migrations for Symfony 4.

**Comment by heather817** [comment]
I don't know, I could spend some time with old code, but we moved on to Symfony 4 and have not had any issues with any versions of migrations for Symfony 4.

**Comment by PReimers** [comment]
Thank you for your feedback.

I'm closing this issue since it seemed fixed in the current version.
