### ISSUE TITLE
get status version in Action

### ISSUE THREAD

**Issue by strauss69400** [doctrine/DoctrineMigrationsBundle#227]
Hi,

Everything is in the title,
I wanted to know if it is possible to have the result of the command doctrine: migration: status directly from an action or a listener.

The goal for me is to get an alert when I log on to my site to tell me that I need to run a migration.
an alert that would appear in a modal for example.

I looked for a solution on the net but I did not find the solution.

Any help is welcome.
Thank you
Best regards

**Comment by jwage** [comment]
You can run the console command from PHP:

```
passthru('./console doctrine:migration:status');
```

Or you could write up the PHP console application for migrations and run the command from within PHP instead of proxying to the command line.
