### ISSUE TITLE
Update Symfony Recipe for 2.0

### ISSUE THREAD

**Issue by Majkl578** [doctrine/DoctrineMigrationsBundle#230]
Recipe will need to be updated for 2.0:
https://github.com/symfony/recipes/tree/master/doctrine/doctrine-migrations-bundle

**Comment by magnetik** [comment]
I just tested 2.0-alpha1, and it seems to work with the same config, so updating it is only copy pasting the `1.3` into a `2.0` folder?

**Comment by stof** [comment]
if the same recipe works already, there is nothing to do.

**Comment by jwage** [comment]
Closing this as it seems there is nothing we need to do. Please re-open if I am incorrect.
