### ISSUE TITLE
This bundle throws an error about un-needed dependency doctrine ORM after installation

### ISSUE THREAD

**Issue by ChangePlaces** [doctrine/DoctrineMigrationsBundle#232]
After installing `doctrine/dbal` and `doctrine/doctrine-migrations-bundle` in a new `symfony/skeleton` project, I see this error:
```
Symfony operations: 3 recipes (578c60b4ddf56f6d595cb6a3655adeca)
  - Configuring doctrine/doctrine-cache-bundle (>=1.3.3): From auto-generated recipe
  - Configuring doctrine/doctrine-bundle (>=1.6): From github.com/symfony/recipes:master
  - Configuring doctrine/doctrine-migrations-bundle (>=1.2): From github.com/symfony/recipes:master
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!
!!  In DoctrineExtension.php line 63:
!!
!!    To configure the ORM layer, you must first install the doctrine/orm package
!!    .
!!
!!
!!
Script @auto-scripts was called via post-update-cmd
```
A call to `bin/console` resulted in the same error.

To resolve this issue I have to manually edit `config/packages/doctrine.yaml` and remove the `orm`section (the code in `DoctrineExtension.php` does not return and continues with the ORM initialisation because the config key for `orm` exists). Does a recipe automatically assume the ORM is also being installed?

**Comment by kejwmen** [comment]
As far as I know there is no way to make decisions based on installed packages inside a recipe, and using doctrine bundle with ORM is a common scenario. 
Recipes are meant to autoconfigure bundles for most popular use cases.

So:
`doctrine/doctrine-migrations-bundle` depends on `doctrine/doctrine-bundle`.
[Doctrine bundle recipe](https://github.com/symfony/recipes/blob/master/doctrine/doctrine-bundle/1.6/config/packages/prod/doctrine.yaml) assumes that orm is installed.

**Comment by ChangePlaces** [comment]
Nothing should be 'assumed' though! That's the issue! Symfony is a lot of components that are separate and independent, not some components that are assumed to be used together with others.

The recipe has to (somehow) take into account that the ORM (which is not a dependency) may not be there

**Comment by xabbuh** [comment]
@ChangePlaces Can you report that over in https://github.com/symfony/recipes? That's the place were the recipe is configured.

**Comment by PReimers** [comment]
**FYI**
They're working on splitting the `doctrine/doctrine-bundle` into `doctrine/dbal-bundle` and `doctrine/orm-bundle` in this issue doctrine/DoctrineBundle#973

**Comment by goetas** [comment]
@ChangePlaces are you sure that you've installed only `doctrine/dbal` and `doctrine/doctrine-migrations-bundle`? (i see that you have `doctrine/doctrine-bundle` and `doctrine/doctrine-cache-bundle` installed).

I'm closing this issue because it might belong to  `doctrine/doctrine-cache-bundle` or  `doctrine/doctrine-bundle` or `symfony/recipes` but certainly not here.
