### ISSUE TITLE
Using private service in migration classes

### ISSUE THREAD

**Issue by lolmx** [doctrine/DoctrineMigrationsBundle#233]
Hello,

I'm using DoctrineMigrationBundle 1.3.1 along Symfony 3.4.

I've searched quite a bit and it looks like the only way to get a service in my migration classes is by implementing the ContainerAwareInterface and getting the service with a `$this->container->get(..)`.

The service that I need in my migration is private and I don't know how to inject it in the migration class.

I tried to declare the migration as a service but it doesn't work (and doesn't sound logic to me anyway).

Does anyone encountered the same issue?

Is this use case handled by the bundle at all? Will it be in version 2.0?

Any help appreciated :)

**Comment by jwage** [comment]
Nothing is planned for 2.0 to be able to handle this. I think you will need to make the service public and locate it with the container.

**Comment by stof** [comment]
You will indeed need to make it public (you can create a public alias for your service and use it here).
Note that I actually discourage using services in migrations, as that might cause issues when your migrations are running later (migrating from an empty DB to the current state executes all migrations using the current codebase). So I would not consider it a priority to make it easier to use DI in migrations

**Comment by lolmx** [comment]
I didn't think about creating a public alias, it should resolve my issue indeed.

Thanks for your responses!
