### ISSUE TITLE
Is App\Migrations recommended as namespace?

### ISSUE THREAD

**Issue by javiereguiluz** [doctrine/DoctrineMigrationsBundle#242]
The official configuration created by Symfony Flex for this bundle says:

    "namespace is arbitrary but should be different from App\Migrations"

(see https://github.com/symfony/recipes/blob/master/doctrine/doctrine-migrations-bundle/1.2/config/packages/doctrine_migrations.yaml#L3)

However, the docs of this bundle uses `App\Migrations` as the namespace. See https://github.com/doctrine/DoctrineMigrationsBundle/blob/master/Resources/doc/index.rst

So, is this a doc issue, a recipe issue ... or is it that I'm not understanding this well? Thanks!

**Comment by jwage** [comment]
I think the namespace can be App\Migrations. I think maybe once upon a time it used to be a problem if the migrations were autoloadable but I don't believe this is the case anymore. Can you test and confirm? If it works, then I think we can generate with App\Migrations as the namespace.

**Comment by ricknox** [comment]
> I think maybe once upon a time it used to be a problem if the migrations were autoloadable but I don't believe this is the case anymore.

That is true. The whole namespacing in Symfony for migrations should be ignored (remove the warning) or perhaps it should be removed (better option imo.) but document that is it arbitrary.

**Comment by alcaeus** [comment]
I updated our configuration to test this. Note that is still on 3.4 without flex, but the configuration is that way regardless.

```
doctrine_migrations:
  dir_name: "%kernel.root_dir%/app_migrations"
  namespace: App\Migrations
  table_name: app_migrations
  name: App Migrations
  custom_template: "%kernel.root_dir%/Resources/migrations.tpl"
```

I tested the process of printing status, generating a migration and running it and didn't encounter any errors (see below). I'd say the documentation can be updated. It's sound advice for bundles but not for standalone applications.

```
alcaeus at vulcan in ~/Code/xxx on test-migration-namespace
$ ./bin/console do:mi:st

 == Configuration

    >> Name:                                               App Migrations
    >> Database Driver:                                    pdo_mysql
    >> Database Name:                                      shop_test
    >> Configuration Source:                               manually configured
    >> Version Table Name:                                 app_migrations
    >> Version Column Name:                                version
    >> Migrations Namespace:                               App\Migrations
    >> Migrations Directory:                               /Users/alcaeus/Code/xxx/app/app_migrations
    >> Previous Version:                                   Already at first version
    >> Current Version:                                    0
    >> Next Version:                                       Already at latest version
    >> Latest Version:                                     0
    >> Executed Migrations:                                0
    >> Executed Unavailable Migrations:                    0
    >> Available Migrations:                               0
    >> New Migrations:                                     0

alcaeus at vulcan in ~/Code/xxx on test-migration-namespace
$ ./bin/console do:mi:ge
Using custom migration template "/Users/alcaeus/Code/xxx/app/Resources/migrations.tpl"
Generated new migration class to "/Users/alcaeus/Code/xxx/app/app_migrations/Version20181115073844.php"

alcaeus at vulcan in ~/Code/xxx on test-migration-namespace [?]
$ ./bin/console do:mi:mi
                                                      
                    App Migrations                    
                                                      

WARNING! You are about to execute a database migration that could result in schema changes and data loss. Are you sure you wish to continue? (y/n)y
Migrating up to 20181115073844 from 0

  ++ migrating 20181115073844

Migration 20181115073844 was executed but did not result in any SQL statements.

  ++ migrated (0.09s)

  ------------------------

  ++ finished in 0.09s
  ++ 1 migrations executed
  ++ 0 sql queries
```

**Comment by jmsche** [comment]
The App\Migrations namespace can be used as it is by default excluded from autowiring/autoconfiguring in services.yaml file: https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/4.2/config/services.yaml

**Comment by javiereguiluz** [comment]
Thank you all for checking this, specially to Andreas for actually trying it. Thanks!
