### ISSUE TITLE
[2.0] MariaDB: The default version column length is too long

### ISSUE THREAD

**Issue by mhujer** [doctrine/DoctrineMigrationsBundle#247]
#### Summary

When MariaDB is used and Migrations 2.0 are installed to a new Symfony application with default Doctrine configuration, creating a migration will fail.

Related issues: https://github.com/doctrine/migrations/issues/514 and https://github.com/doctrine/migrations/pull/538

#### Current behavior

Error message is displayed when creating a migration diff:

```
An exception occurred while executing 'CREATE TABLE migration_versions (version VARCHAR(255) NOT NULL, executed_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', PRIMARY KEY(version)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB':

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
```

#### How to reproduce

1) create a new Symfony application
2) install DoctrineORM + Doctrine Bundle
3) install Migrations Bundle
4) Run `doctrine:migrations:diff`

#### Expected behavior

The `migration_versions` table is created without failing on error.

#### Workaround

Add  `column_length: 14` to `config/packages/doctrine_migrations.yaml`

#### Proposed solution

Change default value in https://github.com/doctrine/DoctrineMigrationsBundle/blob/85d83250655f647b24ce457aeebeba879374d870/DependencyInjection/Configuration.php#L41 from 255 to 14. The [configuration reference ](https://symfony.com/doc/master/bundles/DoctrineMigrationsBundle/index.html#configuration) suggests that the default is 14.

**Comment by jwage** [comment]
Thanks @mhujer! I have made these changes here https://github.com/doctrine/migrations/pull/773 and here https://github.com/doctrine/DoctrineMigrationsBundle/pull/249

**Comment by greg0ire** [comment]
That length is oddly specific. It was introduced in https://github.com/doctrine/DoctrineMigrationsBundle/pull/228/files#diff-fdd764ee72f777e180ace83412a44158R61 , not sure why…

**Comment by jwage** [comment]
I believe it is because the version string we generate by default is 14 characters long.
