### ISSUE TITLE
filter by schema doctrine:migrations:diff 

### ISSUE THREAD

**Issue by walidjlidi** [doctrine/DoctrineMigrationsBundle#253]
is it possible that resulted migration of command php bin/console doctrine:migrations:diff contains only the diff for one schema not all the database.

i think this will be helpful for microservices projects which have schema per microservice. :)

**Comment by jwage** [comment]
Take a look at this https://www.doctrine-project.org/projects/doctrine-migrations/en/2.0/reference/generating-migrations.html#ignoring-custom-tables
