### ISSUE TITLE
Test if Migration Description is set

### ISSUE THREAD

**Issue by alexander-schranz** [doctrine/DoctrineMigrationsBundle#254]
I'm searching for an easy way to get all Migrations and Test if `getDescription` return a value. My Current test is very hacky as I parse the Migration Class File: 

https://gist.github.com/alexander-schranz/e7ab61e7edbcb0c3b46baf6b92921c0f#file-migrationtest-php-L70

**Comment by jwage** [comment]
Hi, thanks for opening this issue. The github issue tracker is used for reporting bugs and feature requests. I am going to go ahead and close this. You can try asking questions in places like [Slack](https://doctrine-project.org/slack) or on Stackoverflow.
