### ISSUE TITLE
php bin/console doctrine:migrations:migrate was failed?

### ISSUE THREAD

**Issue by followyounger** [doctrine/DoctrineMigrationsBundle#259]
WARNING! You have 1 previously executed migrations in the database that are not registered migrations.
    >> 2019-02-26 08:19:17 (20190226081917)

i have tried to execute the "php bin/console doctrine:migrations:version 20190226081917 --delete" ， IT tell this version that is not found. 

but i can not execute this  migrate command.

how should i ?

![image](https://user-images.githubusercontent.com/20137434/53692605-f2a4fe00-3dcd-11e9-9015-70d5fda83726.png)

**Comment by followyounger** [comment]
hope someone who can help me. thx

**Comment by greg0ire** [comment]
I think you can either delete it manually from the database, or you can re-create a migration file with a matching class name and then run the command again.

**Comment by followyounger** [comment]
> I think you can either delete it manually from the database, or you can re-create a migration file with a matching class name and then run the command again.

thanks, it works.

**Comment by PReimers** [comment]
I'm closing this issue since it's resovled.

**Comment by GeneraleCauchemar** [comment]
Just had the same problem, after migrating from Symfony 3.4 to 4.4.
What did the trick for me was to change the namespace of my old migrations to `namespace DoctrineMigrations;`
It was the only difference that I could see between my old migration versions files (that were referenced in the database) and the one I had just generated with `make:migration`.

Hope it helps other people!
