### ISSUE TITLE
Is it possible to set connection for migration in config?

### ISSUE THREAD

**Issue by pyatnitsev** [doctrine/DoctrineMigrationsBundle#263]
Hello!

I looking for way to set Doctrine connection for Migrations in yaml file. Is it possible? 

I use dedicated connection to execute all migrations and add ``--db`` option for each migration-related command is not beautiful. If I can't pass it by config, can I suggest a PR for that? Is it needed anybody else ?

**Comment by jwage** [comment]
There are ways to do it but it is a more custom setup. See: https://www.doctrine-project.org/projects/doctrine-migrations/en/2.0/reference/configuration.html#advanced

DoctrineMigrationsBundle could probably be enhanced to make it a more simple configuration.

**Comment by pyatnitsev** [comment]
I can add `connection` option to configuration of the bundle, that accept string of existed doctrine connection. Ok?

**Comment by pyatnitsev** [comment]
this is clone of #189

**Comment by alcaeus** [comment]
Closing as duplicate of #189.
