### ISSUE TITLE
logical problem in the documentation

### ISSUE THREAD

**Issue by nlhommet** [doctrine/DoctrineMigrationsBundle#266]
Hi,
In the documentation you mention : 

> namespace is arbitrary but should be different from **App\Migrations** as migrations classes **should NOT** be autoloaded

But below the example class has namespace **App\Migrations**, it would have been more logical to put another namespace to avoid confusion.

**Comment by jwage** [comment]
This is outdated now. The namespace can be whatever you want.

**Comment by gnumoksha** [comment]
@jwage I'm wondering what has changed. I thought it was because migrations should only be loaded as development dependencies.
