### ISSUE TITLE
configuration: executed_at_column_name

### ISSUE THREAD

**Issue by landsman** [doctrine/DoctrineMigrationsBundle#272]
missing me, is that `doctrine/migrations:2.1` feature or some legacy stuff?

https://www.doctrine-project.org/projects/doctrine-migrations/en/2.1/reference/configuration.html#line-number-c459741d3ed9c01896dc3d593e7e38d1914332d8-6

`
Unrecognized option "executed_at_column_name" under "doctrine_migrations". Available options are "custom_template", "dir_name", "name", "namespace", "organize_migrations", "table_name".
`

**Comment by landsman** [comment]
Hmm this is works:
```
        "doctrine/doctrine-migrations-bundle": "^2.0",
        "doctrine/migrations": "2.1",
```

**Comment by SenseException** [comment]
Did you find an answer for your question?

**Comment by landsman** [comment]
Yes, previous setup works fine for me, thank you!

**Comment by taixcms** [comment]
I can not handle this error
`Fatal error: Uncaught Symfony\Component\Config\Definition\Exception\InvalidConfigurationException: Unrecognized options "dir_name, namespace" under "doctrine_migrations". Available options are "all_or_nothing", "check_database_platform", "connection", "custom_template", "em", "migrations", "migrations_paths", "name", "organize_migrations", "services", "storage". in /var/www/site.ru/new-spk/vendor/symfony/config/Definition/ArrayNode.php:319 Stack trace: #0 /var/www/site.ru/new-spk/vendor/symfony/config/Definition/BaseNode.php(366): Symfony\Component\Config\Definition\ArrayNode->normalizeValue(Array) #1 /var/www/site.ru/new-spk/vendor/symfony/config/Definition/Processor.php(34): Symfony\Component\Config\Definition\BaseNode->normalize(Array) #2 /var/www/site.ru/new-spk/vendor/symfony/config/Definition/Processor.php(50): Symfony\Component\Config\Definition\Processor->process(Object(Symfony\Component\Config\Definition\ArrayNode), Array) #3 /var/www/site.ru/new-spk/vendor/symfony/dependency-injection/Extension/Ex in /var/www/site.ru/new-spk/vendor/symfony/config/Definition/ArrayNode.php on line 319`
