### ISSUE TITLE
Doctrine ORM Manager named "" does not exist.

### ISSUE THREAD

**Issue by gondo** [doctrine/DoctrineMigrationsBundle#283]
After upgrading from `2.0.0` to the latest `2.1.0` today, migration commands stoped working.
The error message I see in CLI is: `In AbstractManagerRegistry.php line 149: Doctrine ORM Manager named "" does not exist.` 

Any idea what this could be?
No other changes happened, no other package got updated.
I've tested reverting back to `2.0.0` and everything works. Upgrading again to `2.1.0` and things are broken again.

**Comment by alcaeus** [comment]
See #285.

**Comment by gondo** [comment]
Thanks for quick response. To clarify, your PR is fixing the issue, or is it clarifying the error via exceptions messages?

**Comment by alcaeus** [comment]
2.1.1 has been released.
