### ISSUE TITLE
Doctrine ORM Manager named "" does not exist.

### ISSUE THREAD

**Issue by dnl-jst** [doctrine/DoctrineMigrationsBundle#284]
After upgrading my Symfony project I am not able to execute the doctrine migrations migrate command anymore. I updated the dependencies package by package and it stopped after upgrading doctrine/doctrine-migrations-bundle from 2.0.0 to 2.1.0.

I had the same issue in multiple, unrelated Symfony 4.3 projects.

![Bildschirmfoto 2019-11-13 um 13 24 03](https://user-images.githubusercontent.com/712897/68763520-ee95d500-0618-11ea-907b-d2d3b72dd6cc.png)
![Bildschirmfoto 2019-11-13 um 13 24 19](https://user-images.githubusercontent.com/712897/68763525-f190c580-0618-11ea-90ed-2b7d28636f62.png)

**Comment by alcaeus** [comment]
See #285.

**Comment by alcaeus** [comment]
2.1.1 has been released.
