### ISSUE TITLE
Migration Versions table not shown after running 'doctrine:migrations:status'

### ISSUE THREAD

**Issue by ashleyconnor** [doctrine/DoctrineMigrationsBundle#29]
Hello,

I've followed the instructions here http://symfony.com/doc/current/bundles/DoctrineMigrationsBundle/index.html and configured Symfony adding doctrine migrations to the autoload and appkernel.

However when I run 'php app/console doctrine:migrations:status' the output in my terminal shows only the configuration table and not the migration versions table.

Thanks,

Ash

**Comment by mikeSimonson** [comment]
Not sure what the issue was and is probably fixed by now.
