### ISSUE TITLE
Zero downtime migration support

### ISSUE THREAD

**Issue by fchris82** [doctrine/DoctrineMigrationsBundle#292]
We would like to reach the zero downtime deployment. The bottleneck is the database migration. There are existing theoretical solutions for this: https://www.youtube.com/watch?v=hMO63IC6R7c and here is a free book which covers this topic in the Chapter 3: https://developers.redhat.com/books/migrating-microservice-databases-relational-monolith-distributed-data/ .

For this support sometimes we would need 2 different migraiton files (eg: rename or remove column):
- pre deployment
- post deployment

Example:

We have this User Entity:

```php
<?php

namespace Example\UserBundle\Entity;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="user")
 * @ORM\Entity
 */
class User {

    /**
     * @var integer
     *
     * @ORM\Id
     * @ORM\Column(name="user_id", type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255, nullable=false)
     */
    protected $name;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=255, nullable=false)
     */
    protected $email;
}
```

And we want to rename the `email` field to `public_email`:

```php
    /**
     * @var string
     *
     * @ORM\Column(name="public_email", type="string", length=255, nullable=false)
     */
    protected $public_email;
```

Now I can run the `doctrine:migration:diff` command and I will get a new `VersionXXXXXXXXX.php` file. In that case we would get 2 version file, eg:

- `Version20191128125832pre.php` or `Version201911281258320.php` (add an extra `0`)
- `Version20191128125832post.php` or `Version201911281258321.php` (add an extra `1`)

> The numbers at the end may be better because of the natural sort.

Every version class would get a `@preDeploy` and a `@postDeploy` tag:

```php
/**
 * @preDeployment
 */
class Version201911281258320
{
    // ALTER TABLE ... ADD COLUMN public_email DEFAULT NULL, ALGORITHM=INPLACE, LOCK=NONE;
}
```

```php
/**
 * @postDeployment
 */
class Version201911281258321
{
    // In a for cycle: UPDATE ... SET public_email = email WHERE public_email IS NULL LIMIT 1000 <-- this limitation would come from config.
    // ALTER TABLE ... DROP COLUMN email;
}
```

If I want to use the zero downtime support, I could run `pre` and `post` migration files differently:

```shell
$ bin/console doctrine:migration:migrate -n --pre-only
$ make update-source-code
$ bin/console doctrine:migration:migrate -n --post-only
```

Of course, if somebody want to run both of them he/she can call without any option as earlier was used:

```shell
$ bin/console doctrine:migrations:migrate -n
# it runs every new "Version class"
```

This solution is:

- backward compatible
- supports the zero downtime deploy

If you think it may be interesting for you, I can start working on it. But if you think you don't want to implement this feature, I will create a custom bundle.

**Comment by alcaeus** [comment]
My suggestion would be to treat the `pre` and `post` migration files as separate migrations. In a previous project that used migrations, we would only write migrations that did not cause data loss and could thus be reverted and re-applied.

The only issue here is making sure that generated migrations support zero-downtime migrations: this is an almost impossible task in my opinion, so the onus is always on the engineer to make sure the migration works for that deployment concept.

At this time, I'm not even sure this library needs any changes to support this, it may just be a matter of how you use it. 🤔

**Comment by fchris82** [comment]
> The only issue here is making sure that generated migrations support zero-downtime migrations: this is an almost impossible task in my opinion

Please watch the linked video and/or read the linked book (chapter 3). There are scenarios for changing database schema with zero-downtime. I agree, the generated migration files won't be able to cover every situation but most of them coverable. **I want to minimaze the manual steps and coding because of migration.**

>  In a previous project that used migrations, we would only write migrations that did not cause data loss and could thus be reverted and re-applied.

This is a good idea, maybe we could add a `--safe` option for the `doctrine:migrations:diff` command:

```shell
$ bin/console doctrine:migrations:diff --safe
```

In that case the generated migration file wont contains - or contains but commented - any "delete" commands/sql queries.

> I'm not even sure this library needs any changes to support this

Some changes - eg: rename a column - can be "complex" - means: more then one steps. It would be better, if the generated files contain every neccesary steps. Now we would need to do too much manual coding.

**Comment by fchris82** [comment]
Hmmm... Maybe I would have rise up my idea here: https://github.com/doctrine/migrations/ ?

**Comment by goetas** [comment]
I think that https://github.com/doctrine/DoctrineMigrationsBundle/issues/292#issuecomment-559090527 gives the right answer for this question.

Goal for this library is to provide a way to manage the process of running migrations, but it is not responsible for deciding what is inside of those migrations or which side effects do they have on your system (that highly depends on applications and database types).
