### ISSUE TITLE
No changes detected for JoinColumn(onDelete="CASCADE")

### ISSUE THREAD

**Issue by mmarton** [doctrine/DoctrineMigrationsBundle#293]
Hi!

If I add JoinColumn(onDelete="CASCADE") on an existing ManyToOne relationship and run the doctrine:migration:diff command, then i got a "No changes detected in your mapping information." exception.

cache is clean, versions are the latests:

doctrine/annotations                v1.8.0
doctrine/cache                      1.10.0
doctrine/collections                1.6.4
doctrine/common                     v2.11.0
doctrine/data-fixtures              1.4.0
doctrine/dbal                       v2.10.0
doctrine/doctrine-bundle            2.0.2
doctrine/doctrine-fixtures-bundle   3.3.0
doctrine/doctrine-migrations-bundle 2.1.2
doctrine/event-manager              1.1.0
doctrine/inflector                  1.3.1
doctrine/instantiator               1.3.0
doctrine/lexer                      1.2.0
doctrine/migrations                 2.2.0
doctrine/orm                        v2.7.0
doctrine/persistence                1.2.0
doctrine/reflection                 v1.0.0
symfony/doctrine-bridge             v4.3.9

**Comment by dmaicher** [comment]
Whats your version of DoctrineBundle? Likely the you are using 1.12.0 or 2.0.0? There are patch releases that fix a caching issue

**Comment by mmarton** [comment]
> Whats your version of DoctrineBundle? Likely you are using 1.12.0 or 2.0.0? There are new patch releases that fix a caching issue

I updated the question with everything doctrine related. I deleted the cache manually, and run the command, but I got the same result

**Comment by mmarton** [comment]
Hmmm, I deleted it again and it worked this time.
