### ISSUE TITLE
Unrecognized options "dir_name, namespace" under "doctrine_migrations". Available options are "all_or_nothing", "check_database_platform", "connection", "custom_template", "em", "migrations", "migrations_paths", "name", "organize_migrations", "services", "storage"

### ISSUE THREAD

**Issue by taixcms** [doctrine/DoctrineMigrationsBundle#301]
I can not handle this error
Fatal error: Uncaught Symfony\Component\Config\Definition\Exception\InvalidConfigurationException: Unrecognized options "dir_name, namespace" under "doctrine_migrations". Available options are "all_or_nothing", "check_database_platform", "connection", "custom_template", "em", "migrations", "migrations_paths", "name", "organize_migrations", "services", "storage". in /var/www/site.ru/new-spk/vendor/symfony/config/Definition/ArrayNode.php:319 Stack trace: #0 /var/www/site.ru/new-spk/vendor/symfony/config/Definition/BaseNode.php(366): Symfony\Component\Config\Definition\ArrayNode->normalizeValue(Array) #1 /var/www/site.ru/new-spk/vendor/symfony/config/Definition/Processor.php(34): Symfony\Component\Config\Definition\BaseNode->normalize(Array) #2 /var/www/site.ru/new-spk/vendor/symfony/config/Definition/Processor.php(50): Symfony\Component\Config\Definition\Processor->process(Object(Symfony\Component\Config\Definition\ArrayNode), Array) #3 /var/www/site.ru/new-spk/vendor/symfony/dependency-injection/Extension/Ex in /var/www/site.ru/new-spk/vendor/symfony/config/Definition/ArrayNode.php on line 319

**Comment by goetas** [comment]
Please check this thread https://github.com/symfony/orm-pack/pull/22

**Comment by Wojciechem** [comment]
Docs are quite misleading now - doc for 2.0 suggests installing 3.0 (not released yet) and lists these unsupported options happily.
https://symfony.com/doc/master/bundles/DoctrineMigrationsBundle/index.html
I'm using migrations bundle without flex, so linked thread makes 0 sense to me :)

**Comment by goetas** [comment]
There is an issue with the symfony documentation, I've created https://github.com/symfony/symfony-docs/issues/13375

You should install the 2.0, not the 3.0

**Comment by goetas** [comment]
@taixcms  Do you have still this issue?

**Comment by taixcms** [comment]
I removed the migration package, there was no time to solve this problem unfortunately, without the migration package everything works naturally

**Comment by goetas** [comment]
I will close this issue. If you still have any problem feel free to create a new one.

**Comment by camilleterol** [comment]
I had the same problem today. The solution for me was to update the flex recipes for the project with `composer recipes:install --force -v` and then run `composer install`

**Comment by johannesvlot** [comment]
I have the same problem, @camilleterol solution doesn't work for me.
I still get the same error when I run `composer install`

**Comment by jeffsacco** [comment]
Also getting this error when I ran composer update.  Any possible quick fixes to bring a site back up?

**Comment by yakupars** [comment]
Same problem here.
`composer req orm-pack --unpack`
`composer require doctrine/doctrine-migrations-bundle "^2.0"`
did the trick for me...

**Comment by ThomasTr** [comment]
Same problem here with the last upgrade to Symfony 5.1.2 today, 
doctrine/doctrine-migrations-bundle is 3.0.1

**Comment by johannesvlot** [comment]
I changed `"doctrine/doctrine-migrations-bundle":` in `composer.json` to version 2.2.x-dev and then `composer update`

**Comment by AlaaPro** [comment]
> I had the same problem today. The solution for me was to update the flex recipes for the project with `composer recipes:install --force -v` and then run `composer install`

 works for me , thank you

**Comment by jeffsacco** [comment]
> I had the same problem today. The solution for me was to update the flex recipes for the project with `composer recipes:install --force -v` and then run `composer install`

This seemed to work for me this morning.  I hadn't updated my my core in about a month since I was laid off to covid but finally back on the project now.

**Comment by axeljeremy7** [comment]
`//    Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle::class => ['all' => true],`
i try the above and did not work for me.
So I set to this: 
"doctrine/doctrine-migrations-bundle": "2.1.2",
        "doctrine/orm": "2.7.3",

**Comment by guisszo** [comment]
@camilleterol 's solution workef fine for me thanks a lot.

**Comment by theejhay** [comment]
> I had the same problem today. The solution for me was to update the flex recipes for the project with `composer recipes:install --force -v` and then run `composer install`

This worked for me, Thanks.

**Comment by fd6130** [comment]
> Same problem here.
> `composer req orm-pack --unpack`
> `composer require doctrine/doctrine-migrations-bundle "^2.0"`
> did the trick for me...

This worked for me, Thank you.

**Comment by mavykins** [comment]
> 
> 
> I changed `"doctrine/doctrine-migrations-bundle":` in `composer.json` to version 2.2.x-dev and then `composer update`
> That did the trick for me.

Worked for me, worst time deploy a fresh install of symfony 5

**Comment by fd6130** [comment]
Instead of switching back to ^2.0, just update your doctrine_migrations.yaml file.

https://github.com/doctrine/DoctrineMigrationsBundle/blob/master/UPGRADE.md

**Comment by hansgrinwis** [comment]
@camilleterol 's solution works, BUT it overwrites some YAML files, so be sure to check/restore those before commiting. I did not test @fd6130 's solution but it seems that that is all that is required to solve this problem.

**Comment by hansgrinwis** [comment]
Hmmm, while checking `doctrine_migrations.yaml` it appears that `src` is missing from
```
doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/src/Migrations'
```
(and `migrations` in stead of `Migrations`, but that probably does not matter).

**Comment by klodoma** [comment]
> Hmmm, while checking `doctrine_migrations.yaml` it appears that `src` is missing from
> 
> ```
> doctrine_migrations:
>     migrations_paths:
>         'DoctrineMigrations': '%kernel.project_dir%/src/Migrations'
> ```
> 
> (and `migrations` in stead of `Migrations`, but that probably does not matter).

Same issue, this seems to be working.

**Comment by hansgrinwis** [comment]
> 
> 
> Hmmm, while checking `doctrine_migrations.yaml` it appears that `src` is missing from
> 
> ```
> doctrine_migrations:
>     migrations_paths:
>         'DoctrineMigrations': '%kernel.project_dir%/src/Migrations'
> ```
> 
> (and `migrations` in stead of `Migrations`, but that probably does not matter).

`migrations` seems to be the new location for migration files; it was `src/Migrations` in earlier versions.

**Comment by Ananaskirsche** [comment]
@fd6130 solution (described [here](https://github.com/doctrine/DoctrineMigrationsBundle/blob/master/UPGRADE.md)) worked for me.

**Comment by jotarougly** [comment]
> > I had the same problem today. The solution for me was to update the flex recipes for the project with `composer recipes:install --force -v` and then run `composer install`
> 
> This worked for me, Thanks.

Thanks, it work for me too.

**Comment by B3bz** [comment]
@camilleterol thx ! it work

**Comment by anhchienhoang** [comment]
For those who want to upgrade from 2.x to 3.x:

```yaml
doctrine_migrations:
  migrations_paths:
    'DoctrineMigrations': 'path_to_your_migration_folder'

  storage:
    table_storage:
      table_name: 'migration_versions'
      version_column_name: 'version'
      version_column_length: 255
      executed_at_column_name: 'executed_at'
      execution_time_column_name: 'execution_time'
```
Doctrine will automatically add new column `execution_time` and change the version column length for you.

**Comment by CsabaNa** [comment]
Actually the problem within the `symfony/orm-pack` 
as i run the `composer updated` the Doctrine was:
```
  - Downgrading doctrine/migrations (3.0.1 => 2.2.1):  Checking out a3987131fe
  - Downgrading doctrine/doctrine-migrations-bundle (3.0.1 => 2.1.2):  Checking out 856437e8de
``` 
mean while:
```
  - Updating symfony/orm-pack (v1.0.8 => v1.1.0):  Checking out 7dd2ed9ba6
```
so i forced the Doctrine version `^3.0` in the composer.json and got:
```
  - Updating doctrine/migrations (2.2.1 => 3.0.1):  Checking out 69eaf2ca5b
  - Updating doctrine/doctrine-migrations-bundle (2.1.2 => 3.0.1):  Checking out 96e730b0ff
  - Downgrading symfony/orm-pack (v1.1.0 => v1.0.8):  Checking out c9bcc08102
```

So you can decide which is best way for you if you decided to keep the newer version of `orm-pack` you should downgrade the Doctrine configs as well there is a command for it:
```
composer recipes:install --force -v
```
as @camilleterol mentioned 
I choose the first one since it is a smaller step between `orm-pack`s but huge(downgrade) for Doctrine

**Comment by nicolas-grekas** [comment]
Check https://github.com/symfony/orm-pack/issues/29

**Comment by azhararmar** [comment]
> I had the same problem today. The solution for me was to update the flex recipes for the project with `composer recipes:install --force -v` and then run `composer install`

When I run this, it resets and overwrite the services.yaml file, which is an issue to me.

**Comment by walikparis** [comment]
First i got this error message:
Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter::__construct() must be an instance of Doctrine\Common\Persistence\ManagerRegistry or null, instance of Doctrine\Bundle\DoctrineBundle\Registry given, called in /script/var/cache/dev/ContainerUM9ENIp/App_KernelDevDebugContainer.php on line 5402”

So i did a:
composer remove orm-pack
composer require orm-pack

Then i got this error message:
“Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter::__construct() must be an instance of Doctrine\Common\Persistence\ManagerRegistry”

Which i finaly resolved by updating composer.json : 
 "doctrine/doctrine-migrations-bundle": "^2.0",

So thanks to both yakupars and johannesvlot for tricks

**Comment by Dahkenangnon** [comment]
> > I had the same problem today. The solution for me was to update the flex recipes for the project with `composer recipes:install --force -v` and then run `composer install`
> 
> This worked for me, Thanks.

Thank. This solve the problem

**Comment by eacevedof** [comment]
> Hmmm, while checking `doctrine_migrations.yaml` it appears that `src` is missing from
> 
> ```
> doctrine_migrations:
>     migrations_paths:
>         'DoctrineMigrations': '%kernel.project_dir%/src/Migrations'
> ```
> 
> (and `migrations` in stead of `Migrations`, but that probably does not matter).

thnx this worked for me.
https://github.com/eacevedof/prj_shopech#actualizaci%C3%B3n-composer-update

**Comment by AmaralMarti** [comment]
> Hmmm, while checking `doctrine_migrations.yaml` it appears that `src` is missing from
> 
> ```
> doctrine_migrations:
>     migrations_paths:
>         'DoctrineMigrations': '%kernel.project_dir%/src/Migrations'
> ```
> 
> (and `migrations` in stead of `Migrations`, but that probably does not matter).

Thanks!
This worked for me.

**Comment by zoomtronic** [comment]
> Hmmm, while checking `doctrine_migrations.yaml` it appears that `src` is missing from
> 
> ```
> doctrine_migrations:
>     migrations_paths:
>         'DoctrineMigrations': '%kernel.project_dir%/src/Migrations'
> ```
> 
> (and `migrations` in stead of `Migrations`, but that probably does not matter).

Worked for me when migrating from symfony 4.1 to symfony 4.4

**Comment by benodeveloper** [comment]
> > Hmmm, while checking `doctrine_migrations.yaml` it appears that `src` is missing from
> > ```
> > doctrine_migrations:
> >     migrations_paths:
> >         'DoctrineMigrations': '%kernel.project_dir%/src/Migrations'
> > ```
> > 
> > 
> > (and `migrations` in stead of `Migrations`, but that probably does not matter).
> 
> `migrations` seems to be the new location for migration files; it was `src/Migrations` in earlier versions.

this works for me 
i just replace  this in my config\packages\doctrine_migrations.yaml file

**Comment by jmada** [comment]
> I had the same problem today. The solution for me was to update the flex recipes for the project with `composer recipes:install --force -v` and then run `composer install`

Thank you so much! It worked like a charm!
