### ISSUE TITLE
Make clear that migrations require 64bit

### ISSUE THREAD

**Issue by arneee** [doctrine/DoctrineMigrationsBundle#302]
Hi,

I was spending quite some time today figuring out why I was not able to rollback a migration. Turns out that doctrine migrations - and therefore this bundle - requires a 64 bit version of PHP and I had, for some reason, still PHP 7.2.10 ZTS MSVC15 (Visual C++ 2017) x86 installed.

Shouldn't it be noted somewhere that 64 bit are required? 

Original issue in the doctrine project: https://github.com/doctrine/migrations/pull/854

**Comment by goetas** [comment]
that will not be the case anymore in 3.0

**Comment by arneee** [comment]
I know, but 3.0 is not released yet and I was spending at least two hours figuring out what's wrong

**Comment by goetas** [comment]
which version of the doctrine/migrations package are you using? were you getting any error?

**Comment by arneee** [comment]
The latest one (2.2.1) via the symfony migrations bundle (2.1.2) on Symfony 4.4.5

The error message is just "Could not find any migrations to execute". 

In the PR linked, you will find the calculateDirection function, which on 32bit systems comes to the conclusion that both versions are the same and therefore defaults to the "up" direction, even when it actually should go down. 

I was trying to revert a migration and could not get it working.

**Comment by goetas** [comment]
As of https://github.com/doctrine/DoctrineMigrationsBundle/releases/tag/3.0.0-alpha.1 migrations are strings, so no more issues related to integer overflow
