### ISSUE TITLE
The parameter "doctrine_migrations.dir_name" has a dependency on a non-existent parameter "kernel.root_dir"

### ISSUE THREAD

**Issue by emodric** [doctrine/DoctrineMigrationsBundle#305]
When using Doctrine Migrations Bundle 2.1 on Symfony 5 with default config, the above error message is emmited due to DI configuration class using `kernel.root_dir` parameter to build a default value for `root_dir` param.

**Comment by alcaeus** [comment]
See https://github.com/doctrine/DoctrineMigrationsBundle/pull/295 for a previous attempt at fixing this and related discussion.

**Comment by emodric** [comment]
Whoops, sorry for the new issue, tried to search through issues with `root_dir` and failed :)

Should I close this?

**Comment by emodric** [comment]
So the consensus is just make sure that the parameter is configured, right?

**Comment by xabbuh** [comment]
As I stated in https://github.com/doctrine/DoctrineMigrationsBundle/pull/295#discussion_r367819343 I think a forward-compatible upgrade path could be this:

> I think the only safe upgrade path is to deprecate not configuring this option and making it a mandatory one in the next major release.

**Comment by emodric** [comment]
Thanks @xabbuh !

Will close this one!
