### ISSUE TITLE
The child node "migrations_paths" at path "doctrine_migrations" must be configured.

### ISSUE THREAD

**Issue by emodric** [doctrine/DoctrineMigrationsBundle#310]
When bundle v3 is installed but not configured, the error:

> The child node "migrations_paths" at path "doctrine_migrations" must be configured.

is thrown.

We have an app which by itself does not use migrations, but it does use a library which uses doctrine migrations to manage its DB tables (by providing the config directly via command line). In this situation, the default configuration for Doctrine Migrations Bundle in the app itself does not exist, since the app is completely unaware of the bundle.

It would be helpful in these cases to allow the default configuration without paths, or, if possible, check for paths only if `migrations_paths` config is actually used in a configuration file.

**Comment by goetas** [comment]
Does this library uses the doctrine/migrations or doctrine/doctrine-migrations-bundle package?

**Comment by emodric** [comment]
`composer.json` states the bundle as the dependency, and requires it to be activated because we use the `doctrine:migrations:migrate` command in install and upgrade instructions.

**Comment by goetas** [comment]
Well, if you use the library but the bundle commands, things might not work.

**Comment by goetas** [comment]
Can you please explain a bit more on how doctrine migrations is used and configured in your application?

**Comment by goetas** [comment]
Looking at your profile and company page, I think that you might benefit from reading https://www.goetas.com/blog/multi-namespace-migrations-with-doctrinemigrations-30/

**Comment by emodric** [comment]
You have a Symfony app, fairly regular, doesn't need access to a database so no Doctrine is used at all.

If you wish to install our bundle, which uses Migrations to manage the DB tables, one of the steps is to run Migrations. To make the install process easier for the users, and to not require them to add Migrations config to their main `config/packages`, we have the following step:

```
https://docs.netgen.io/projects/layouts/en/latest/getting_started/install_new_symfony.html#install-the-database
```

```
php bin/console doctrine:migrations:migrate --configuration=vendor/netgen/layouts-core/migrations/doctrine.yaml
```

where the yaml file is:

```
name: Netgen Layouts Migrations
migrations_namespace: Netgen\Layouts\Migrations\Doctrine
table_name: nglayouts_migration_versions
migrations_directory: Doctrine
```

In v2, this works without issues, even if the Symfony app you're installing the bundle on, never even used Migrations and has no previous config. The command will just take the config from the provided file and run it.

This does not work on v3 any more. This issue is most likely related to #311 (and if it is, this one may be closed), where our custom configuration specified by `--configuration` while using `doctrine:migrations:migrate` config is completely ignored in v3.

**Comment by emodric** [comment]
@goetas Is there a chance this could also be implemented? Basically, making sure that the app does not crash if we install Migrations, but do not configure them (for purposes described in #311).

**Comment by goetas** [comment]
see https://github.com/doctrine/DoctrineMigrationsBundle/pull/316

**Comment by emodric** [comment]
Thank you  this is great!
