### ISSUE TITLE
[3.0-alpha] Container-aware migrations

### ISSUE THREAD

**Issue by pamil** [doctrine/DoctrineMigrationsBundle#314]
I'm currently trying to run Sylius with a couple of plugins using 3.0-alpha and existing migrations extending `ContainerAwareInterface` stopped working.

There are a few cases in which we need to access a parameter or a service from the container. An example: 
1. We have `name` on `product_variant`
2. We want to make it translatable by adding `product_variant_translation` table `(id, product_variant_id, locale, name)` and removing `name` from `product_variant`
3. We need to create rows in `product_variant_translation` with `name` taken from related `product_variant` and locale being `%locale%` parameter taken from the container

In these cases, being able to access the container or having some other way to inject parameters and services is really helpful.

**Comment by goetas** [comment]
You can provide a custom migration factories, that can provide the container or any other needed dependency. I have blogged about it in https://www.goetas.com/blog/multi-namespace-migrations-with-doctrinemigrations-30/#extra%3A-custom-migration-factories-aka-decorating-services (see `Extra: Custom migration factories (aka Decorating services)` section)

**Comment by alcaeus** [comment]
We might want to provide such a factory for convenience sake in the bundle 🤔

**Comment by goetas** [comment]
hmmm... here the question comes. Is it better to have `ContainerAwareInterface` migrations or to allow proper dependency injection any pass the dependencies via migration consturctor?

Wasn't `ContainerAwareInterface` deprecated?

**Comment by alcaeus** [comment]
If you can make proper dependency injection work, that's even better. That would require making migration services as was done for fixtures a while back.

**Comment by pamil** [comment]
Thanks a lot for the quick reply! Migration factory sounds good and I will help me move forward with testing.

As for making it built-in, dependency injection sounds like the best solution, I try to avoid `ContainerAwareInterface` as much as I can.

In FriendsOfBehat/SymfonyExtension we have a similar logic - if a service with id equal to context class exists, it uses the service; if it doesn't, it creates an instance based on the class name.

**Comment by goetas** [comment]
Dependency injection is already possibile, is just about providing a proper factory.
I guess that some built in factories can be provided in future feature releases

**Comment by pamil** [comment]
Btw. the blogpost snippet for container-aware factory needs some adjustments to work:

```yaml
App\Core\ProjectVersionFactory.inner:
        class: Doctrine\Migrations\Version\MigrationFactory
        factory: ['@doctrine.migrations.dependency_factory', 'getMigrationFactory']
```

Added `class` option and `@` in the first factory argument.

**Comment by goetas** [comment]
Thanks, will fix that

**Comment by goetas** [comment]
Closing as this feature is already available. and the issue reported on my blog has been fixed.

As a note, https://github.com/doctrine/DoctrineMigrationsBundle/pull/323 should improve even more the possibility to provide more external services into the migrations library.
