### ISSUE TITLE
Release 2.2

### ISSUE THREAD

**Issue by emodric** [doctrine/DoctrineMigrationsBundle#315]
Hi,

what is the plan for 2.2 release which contains forward compatibility layer for Migrations v3?

Thanks!

**Comment by goetas** [comment]
2.2 will be tagged a bit after 3.0.0.

It is mainly to allow 3.0 to make changes and to not have to change multiple times the forward layer

**Comment by emodric** [comment]
@goetas Now that 3.0 is released, will 2.2 be released soon?

**Comment by goetas** [comment]
currently the focus in fixing some of the issues with the 3.0 release, when those will be sorted out we will have resources to work in the next feature release for 2.x

**Comment by goetas** [comment]
Closing this to allow doctrine bot to tag the 2.2.0 release
