### ISSUE TITLE
Release 3.0 timeline

### ISSUE THREAD

**Issue by weaverryan** [doctrine/DoctrineMigrationsBundle#321]
Hi!

I've already been playing with doctrine/migrations 3.0 and bundle 3.0. I will, in the next few weeks, record the Symfony 5 database tutorial for SymfonyCasts. I would love to be able to have that tutorial use v3 of migrations. Do you have any expectations on when v3 of the library and bundle would be released?

Thanks!

**Comment by goetas** [comment]
The beta release should happen in the next 2-3 weeks. after that there should be no more breaking changes. The stable release should be released ~1 month after the beta.

**Comment by weaverryan** [comment]
Ok then, I'll have to plan to do the tutorial on the old version and do my best to mention the upcoming changes.

Cheers!
