### ISSUE TITLE
Migration to 3.0.0-beta

### ISSUE THREAD

**Issue by mhitza** [doctrine/DoctrineMigrationsBundle#325]
I've tried to follow the steps described in the migration guide. I've even included the `storage` section in my `doctrine_migrations.yml` but whatever command I try to run I'm constantly facing the same error:

```
In MetadataStorageError.php line 13:
                                                                                                           
  The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue.
```

Even when I try to run the said command:
```shell
$ php bin/console doctrine:migrations:sync-metadata-storage 

In MetadataStorageError.php line 13:
                                                                                                           
  The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue.
```

**Comment by goetas** [comment]
Do you have some custom type mappings on the DBAL typed for date time fields, integers or strings?

**Comment by mhitza** [comment]
@goetas it was a classic PEBKAC situation. In the end, I figured out that the issue stemmed from the fact that I use MariaDB instead of MySQL but my `DATABASE_URL` configuration was misconfigured. After I've changed the `serverVersion` to `mariadb-10.3.17` it all worked just fine.

There are minor differences between a few default properties set in MariaDB but not in MySQL, and when the `migration_versions` table was checked it always found a TableDiff. For future reference I'm attaching some diff screenshots. On the left is the table information as read from the database and on the right the expected table.

![doctrine-version](https://user-images.githubusercontent.com/273079/83271105-11ad5e00-a1d2-11ea-93b1-833ddbd54932.png)

![doctrine-executed-at](https://user-images.githubusercontent.com/273079/83271115-16721200-a1d2-11ea-95e7-b83ab0335640.png)

![doctrine-execution-time](https://user-images.githubusercontent.com/273079/83271133-1a059900-a1d2-11ea-8bff-72721410debc.png)

![doctrine-index](https://user-images.githubusercontent.com/273079/83271149-1eca4d00-a1d2-11ea-8fa7-e9c36ab0ec0f.png)

**Comment by mhitza** [comment]
@stof I'd leave it open for a bit more, as I've encountered another error and I'm debugging it for a bit before reporting back. I'll close it myself if it's another configuration problem :+1:

**Comment by mhitza** [comment]
Ok, so the error I saw is just the new message shown when there are no migrations left to run  https://github.com/doctrine/migrations/commit/3cb3932d85caed3d0016208abe1f2440f9f650d5 , and now it's reported as

```
[ERROR] The version "latest" couldn't be reached, you are at version "DoctrineMigrations\Version20200528224224"
```

In my opinion, the error message used previously was straightforward, this one confused me a bit. But at least everything works fine now!
