### ISSUE TITLE
Unrecognized options "dir_name, namespace" under "doctrine_migrations"

### ISSUE THREAD

**Issue by vlad57** [doctrine/DoctrineMigrationsBundle#328]
Hi !

I got this issue when I'm running composer install :

Unrecognized options "dir_name, namespace" under "doctrine_migrations". Available options are "all_or_nothing", "check_database_platform", "connection", "custom_template", "em", "factories", "migrations", "migrations_paths", "organize_migrations", "services", "storage".

Thanks for your help,

**Comment by velreine** [comment]
Your dependency probably got updated to use DoctrineMigrations@3.x
check: https://www.doctrine-project.org/projects/doctrine-migrations/en/latest/reference/configuration.html

**Comment by vlad57** [comment]
Thank you for your help, 

I rather followed this link : https://symfony.com/doc/master/bundles/DoctrineMigrationsBundle/index.html

And took the configuration for doctrine_migrations.yaml file.

Have a nice day.
