### ISSUE TITLE
[DIC] Allow parameter injection

### ISSUE THREAD

**Issue by Guikingone** [doctrine/DoctrineMigrationsBundle#332]
Hi everyone 👋 

Small question about the migration files that can require specific configuration parameters (things like a version flag, etc), actually, we can use `ContainerAwareInterface` but is there any plan to support things like the `bind` key or even parameters injection in the migration files? 🤔 

Thanks again for the feedback and have a great day 🙂 

PS: Here's a small example that I have in mind

```php
<?php 

// ...

class fooMigration extends AbstractMigration
{

    // ...

    public function setVersion(string $version) 
    { 
        $this->version = $version;
    }

    public function up(Schema $schema): void
    {
        if ('2.3' === $this->version) {
            $this->addSql('// ....');
        }
    }
}
```

**Comment by goetas** [comment]
You can achieve that already with custom factories. 

I wrote a blog post on how to do it https://www.goetas.com/blog/multi-namespace-migrations-with-doctrinemigrations-30/#extra%3A-custom-migration-factories-aka-decorating-services
