### ISSUE TITLE
Upgrade From 2.x to 3.0.0 missing docs about using `custom` template

### ISSUE THREAD

**Issue by tarlepp** [doctrine/DoctrineMigrationsBundle#333]
I have been used some custom template for migrations and seems like there is change that is missing from UPGRADE.md

Earlier:
`final class Version<version> extends AbstractMigration`
With 3.x:
`final class <className> extends AbstractMigration`

**Comment by goetas** [comment]
fixed in https://github.com/doctrine/DoctrineMigrationsBundle/pull/334
