### ISSUE TITLE
Unrecognized options "dir_name, namespace" under "doctrine_migrations"

### ISSUE THREAD

**Issue by Krazitchek** [doctrine/DoctrineMigrationsBundle#338]
Error on Symfony cache:clear when composer update Symfony 5.1.1 to 5.1.2:

Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In ArrayNode.php line 320:
!!                                                                                 
!!    Unrecognized options "dir_name, namespace" under "doctrine_migrations". Ava  
!!    ilable options are "all_or_nothing", "check_database_platform", "connection  
!!    ", "custom_template", "em", "factories", "migrations", "migrations_paths",   
!!    "organize_migrations", "services", "storage".                                
!!                                                                                 
!!  
!!  
Script @auto-scripts was called via post-update-cmd

**Comment by tarlepp** [comment]
See https://github.com/doctrine/DoctrineMigrationsBundle/blob/master/UPGRADE.md

**Comment by simivar** [comment]
I think that somewhere in chain of `orm-pack` -> `DoctrineMigrationsBundle` -> `DoctrineMigrations` BC break has been introduced. I've got a project with `"symfony/orm-pack": "^1.0",` which worked perfectly until today after running simple `composer update`. I got the same error as author on pretty new project (created 24 days ago) even though I didn't change any constraints in `composer.json` file. Out of the blue I see this:

```bash
  - Updating doctrine/migrations (2.2.1 => 3.0.0): Loading from cache
  - Updating doctrine/doctrine-migrations-bundle (2.1.2 => 3.0.1): Loading from cache
```

**Comment by Krazitchek** [comment]
OK, the first After/Before in https://github.com/doctrine/DoctrineMigrationsBundle/blob/master/UPGRADE.md resolve this case. Composer update no more give this error. Thank you.

**Comment by tseho** [comment]
There is no version constraints in `orm-pack`, see https://github.com/symfony/orm-pack/blob/3644badedf565a5a0ff6b1cba117daee4bf7bdfc/composer.json

IMHO, you should unpack.
It's perfectly normal for Doctrine to introduce BC breaks in major versions and it's a really bad idea to use `"*"` as a dependency constraint.

**Comment by CsabaNa** [comment]
Actually the problem within the `symfony/orm-pack` 
as i the `composer updated` the Doctrine was:
```
  - Downgrading doctrine/migrations (3.0.1 => 2.2.1):  Checking out a3987131fe
  - Downgrading doctrine/doctrine-migrations-bundle (3.0.1 => 2.1.2):  Checking out 856437e8de
``` 
mean while:
```
  - Updating symfony/orm-pack (v1.0.8 => v1.1.0):  Checking out 7dd2ed9ba6
```
so i forced the Doctrine version and got in the composer.json:
```
  - Updating doctrine/migrations (2.2.1 => 3.0.1):  Checking out 69eaf2ca5b
  - Updating doctrine/doctrine-migrations-bundle (2.1.2 => 3.0.1):  Checking out 96e730b0ff
  - Downgrading symfony/orm-pack (v1.1.0 => v1.0.8):  Checking out c9bcc08102
```

So you can decide which is best way for you if you decided to keep the newer version of `orm-pack` you should downgrade the Doctrine configs as well there is a command for it:
```
composer recipes:install --force -v
```

**Comment by nicolas-grekas** [comment]
@CsabaNa check https://github.com/symfony/orm-pack/issues/29
