### ISSUE TITLE
Missing `injectContainerToMigrations` when upgrading to 3.0.0

### ISSUE THREAD

**Issue by jtaylor100** [doctrine/DoctrineMigrationsBundle#342]
After upgrading to 3.0.0 in our application and making changes as per the documentation (adding configuration), we are experiencing this error when running the migrate command:

```
[error] Migration Application\Migrations\Version20190123151439 failed during Execution. Error: "Call to a member function getParameter() on null"

In Version20190123151439.php line 41:
                                                    
  [Error]                                           
  Call to a member function getParameter() on null  
                                                    
```

Version20190123151439 is an older migration and the line causing the error was a call to the container, which is expected to be injected onto the migration since it has the `ContainerAwareInterface` and `ContainerAwareTrait`. This suggests that the container is no longer being injected in 3.0.0.

The previous code that does the injection was found in `DoctrineCommand::injectContainerToMigrations` which no longer exists after the upgrade.

Is this loss of functionality intentional? Is it documented anywhere?

**Comment by phucwan91** [comment]
it might help https://www.goetas.com/blog/multi-namespace-migrations-with-doctrinemigrations-30/#extra%3A-custom-migration-factories-aka-decorating-services

**Comment by jtaylor100** [comment]
Thanks, I suppose this is a duplicate of #314.

**Comment by goetas** [comment]
There is a similar discussion also in https://github.com/doctrine/DoctrineMigrationsBundle/issues/336
