### ISSUE TITLE
[3.X] Migrations with ContainerAwareInterface missing?

### ISSUE THREAD

**Issue by piegus** [doctrine/DoctrineMigrationsBundle#349]
Hi. Is there possibility to define migrations with ability to import parameters or inject some services ?
I don't see any mention of it in new version 3.x. 

In 1.x I was able to import parameters in my migration version.

**Comment by goetas** [comment]
Please see https://github.com/doctrine/DoctrineMigrationsBundle/pull/348

**Comment by goetas** [comment]
closed by https://github.com/doctrine/DoctrineMigrationsBundle/pull/348
