### ISSUE TITLE
[3.0]Custom migration factory 

### ISSUE THREAD

**Issue by tymon82** [doctrine/DoctrineMigrationsBundle#350]
In doctrine_migration.yaml got

` services:
        'Doctrine\Migrations\Version\MigrationFactory': 'App\Core\ProjectMigrationFactory'`

in services.yaml:

`App\Core\ProjectMigrationFactory.inner:
      class: Doctrine\Migrations\Version\DbalMigrationFactory
      factory: ['@doctrine.migrations.dependency_factory', 'getMigrationFactory']
      
    App\Core\ProjectMigrationFactory:
      arguments: ['@App\Core\ProjectMigrationFactory.inner', '@service_container']`

And defined factory class:

`<?php

declare(strict_types=1);

namespace App\Core;

use Doctrine\Migrations\AbstractMigration;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Doctrine\Migrations\Version\MigrationFactory;

class ProjectMigrationFactory implements MigrationFactory
{
    private $container;
    private $migrationFactory;
    
    public function __construct(MigrationFactory $migrationFactory, ContainerInterface $container)
    {
        $this->container = $container;
        $this->migrationFactory = $migrationFactory;
    }
    
    public function createVersion(string $migrationClassName): AbstractMigration
    {
        $instance = $this->migrationFactory->createVersion($migrationClassName);
        
        if ($instance instanceof ContainerAwareInterface) {
            $instance->setContainer($this->container);
        }
        
        return $instance;
    }

}`

When try to execute migration got memory limit error:

`Fatal error: Allowed memory size of 4294967296 bytes exhausted (tried to allocate 20480 bytes) in /var/www/project/vendor/doctrine/migrations/lib/Doctrine/Migrations/DependencyFactory.php on line 309
PHP Fatal error:  Allowed memory size of 4294967296 bytes exhausted (tried to allocate 20480 bytes) in /var/www/project/vendor/symfony/error-handler/ErrorHandler.php on line 653
`

**Comment by goetas** [comment]
https://github.com/doctrine/DoctrineMigrationsBundle/pull/348 documents how you should provide custom migration factories , can you please try it?

**Comment by tymon82** [comment]
@goetas in newest version of docs works properly please put it do offical docs ASAP because i spend a day to find out how to inject container

**Comment by TheFox** [comment]
@goetas Where does #348 document the custom migration factories? You mean in [Resources/doc/index.rst](https://github.com/doctrine/DoctrineMigrationsBundle/blob/7f0cd24eb614fb1a20489f507bdd5290ea1b7cfa/Resources/doc/index.rst)?

**Comment by goetas** [comment]
@TheFox if you look in the diff of #348  you should see an example on how to create a custom migration factory.
