### ISSUE TITLE
doctrine:migrations:diff generates different code for the same columnDefinition statement

### ISSUE THREAD

**Issue by goodjinny** [doctrine/DoctrineMigrationsBundle#353]
Have an Entity:
<pre><code>
class IClientBill
{
    .....
    /**
     * @ORM\Column(type="string", columnDefinition="CHAR(12) NOT NULL", unique=true)
     */
     protected $hash;
    .....
}
</code></pre>
After first time running **doctrine:migrations:diff** it generates a correct SQL migration with `hash CHAR(12) NOT NULL` statement, as defined in columnDefinition:
<pre><code>
 $this->addSql('CREATE TABLE iclient_bill (id INT NOT NULL, client_id INT NOT NULL, month DATE NOT NULL, amount DOUBLE PRECISION NOT NULL, payed BOOLEAN NOT NULL, hash CHAR(12) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
</code></pre>
But, after the second time **doctrine:migrations:diff** it tries to change previous definition for `hash` column:
<pre><code>
$this->addSql('ALTER TABLE iclient_bill ALTER hash TYPE VARCHAR(255)');
</code></pre>
which is  not correct. What could be the problem?

**Comment by dvdknaap** [comment]
I got the same issue for a few months now it's even in the latest version.

I've got this with enum fields and with fields that got a comment so i guess it's caused by columns with an 'columnDefinition'

**Comment by goetas** [comment]
This is a https://github.com/doctrine/dbal issue (and probably related to the particular database you might be using).
Please create a report on the dedicated repo.
