### ISSUE TITLE
Unrecognized options "migrations_paths, storage" under "doctrine_migrations"

### ISSUE THREAD

**Issue by hrochniak** [doctrine/DoctrineMigrationsBundle#354]
Hello, we had issue with configuration file a month ago. After reading UPGRADE.md there was change in configuration key names, which we followed and everything was working. But after latest update, we run into similar problem:

> Unrecognized options "migrations_paths, storage" under "doctrine_migrations". Available options are "all_or_nothing", "column_length", "column_name", "custom_template", "dir_name", "executed_at_column_name", "name", "namespace", "organize_migrations", "table_name".

Was there any other change in configuration file, which needs to be followed?

Thanks.

**Comment by goetas** [comment]
Can you please share your yaml file?

**Comment by hrochniak** [comment]
I just found that `composer update` installed package version 2.*, not 3.*. That was the reason why it did not recognize the "new" configuration naming. It was resolved by adding ^3.0 to composer.json.
