### ISSUE TITLE
setDeprecated() warning in Symfony 5.1

### ISSUE THREAD

**Issue by 01e9** [doctrine/DoctrineMigrationsBundle#356]
https://github.com/doctrine/DoctrineMigrationsBundle/blob/5efa29df768abaafe29b34e73dac68efbedcaa4d/DependencyInjection/Configuration.php#L46

[This code](https://github.com/symfony/config/blob/3448649b5e61ddfb1e4a1c7fc2983b365ff622c1/Definition/Builder/NodeDefinition.php#L175-L176) triggers the warning.

**Comment by pchelk1n** [comment]
same

**Comment by goetas** [comment]
solved in https://github.com/doctrine/DoctrineMigrationsBundle/pull/357

**Comment by acasademont** [comment]
Hi @goetas could a new bugfix release be tagged soon? Thank you!

**Comment by Zilus** [comment]
Any news on this? I know its fixed but not released (still v2.2.0).

Thanks!

**Comment by acasademont** [comment]
Maybe @greg0ire can help us on this one...A bugfix 2.2.1 release would be much appreciated, than you!

**Comment by greg0ire** [comment]
I released 2.2.1 :slightly_smiling_face:

**Comment by oleg-brizy** [comment]
I started using 3.0 :confused:

**Comment by greg0ire** [comment]
Don't worry, we will merge this up eventually.
