### ISSUE TITLE
BC 3.0.0 is not compatible with AWS Aurora Serverless MySQL

### ISSUE THREAD

**Issue by mcn-fredw** [doctrine/DoctrineMigrationsBundle#361]
AWS Aurora Serverless MySQL is based on MySQL 5.6. The minimum version column length of 1024 makes a key longer than allowed by MySQL 5.6.
```
An exception occurred while executing 'CREATE TABLE doctrine_migration_vers  
  ions (version VARCHAR(1024) NOT NULL, executed_at DATETIME NOT NULL COMMENT  
   '(DC2Type:datetime_immutable)', PRIMARY KEY(version))
   DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB':                           
                                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
```
I tried to change the column length in the package config back to 14, but got an error that 1024 is the minimum length.
```
In BaseNode.php line 471:
                                                                               
  Invalid configuration for path "doctrine_migrations.storage.table_storage.v  
  ersion_column_length": The minimum length for the version column is 1024.    
                                                                               

In ExprBuilder.php line 187:
                                                      
  The minimum length for the version column is 1024.  
```
Looking at doctrine/migrations 3.0 upgrade documentation, they show a version column length of 191.
https://github.com/doctrine/migrations/blob/master/UPGRADE.md

**Comment by goetas** [comment]
Are you using 3.0.0 or one of the most recent Bugfix releases? The issue is that the error message you are reporting is only present into the  2.x branch, not 3.x.


BTW, that check should be removed in 2.x too, it is a bug

**Comment by mcn-fredw** [comment]
Ahh, I see now. one of our devs had the bundle in require (^2.0) and
require-dev (^3.1).
When fixing that issue, must have left the ^2.0 one in, which gave us the
latest 2.x branch.
I downgraded to ^2.0.0 and it's working fine now.
Usually with semantic versioning, the major number is change for breaking
changes, So I assumed it was the 3.0 branch that had the problem.
AWS Serverless Aurora does support MySQL 5.7 now, so we can upgrade before
trying again.
