### ISSUE TITLE
PHP8 Support

### ISSUE THREAD

**Issue by thiagocordeiro** [doctrine/DoctrineMigrationsBundle#362]
PHP8 is coming up and a RC version is already available, would be great to have this library available also for this new version

**Comment by highlyprofessionalscum** [comment]
any news?

**Comment by TheHett** [comment]
@highlyprofessionalscum you can check and follow PR above

**Comment by bnymn** [comment]
Check this PR: #383

**Comment by julienmiclo** [comment]
Can't update my packages => doctrine/doctrine-migrations-bundle[3.0.0, ..., 3.0.1] require php ^7.2 -> your php version (8.0.0) does not satisfy that requirement.
Someone know when PR #383 will be accepted ?

**Comment by jdreesen** [comment]
When all its dependencies are compatible with PHP 8.

**Comment by alcaeus** [comment]
3.0.2 will support PHP 8 (see #390). We are still not sure whether 2.x will support PHP 8, as the base library has some issues that need addressing before we can support it there. If you need support for PHP 8 in doctrine/migrations 2.x, please read https://github.com/doctrine/migrations/issues/1048#issuecomment-750291792. I'm closing this issue and we'll revisit the topic if 2.x will become compatible in the future.
