### ISSUE TITLE
MigrationsDiffDoctrineCommand may not inherit from DiffCommand

### ISSUE THREAD

**Issue by philiprabbett** [doctrine/DoctrineMigrationsBundle#371]
**Version 3.0.1**

In MigrationsDiffDoctrineCommand.php line 59:
                                                                                                                                                                                        

> Compile Error: Class Doctrine\Bundle\MigrationsBundle\Command\MigrationsDiffDoctrineCommand may not inherit from final class (Doctrine\Migrations\Tools\Console\Command\DiffCommand)

https://github.com/doctrine/migrations/pull/944

**Comment by ne0h12** [comment]
Up!

**Comment by Cartman34** [comment]
I am also having this issue with the last versions from composer, so `php bin/console make:migration` is no more working !!

As quick fix for dev environment, I edited DiffCommand and apply:
- Remove _final_
- Set return of _execute_ method to _?int_ (instead of just _int_)

**Comment by goetas** [comment]
it seems that you have extended `MigrationsDiffDoctrineCommand`, I suggest to not extend it, and to create your own command implementing what is needed for your specific use case.
