### ISSUE TITLE
Cannot create Symfony session database table with migrations

### ISSUE THREAD

**Issue by 4d4ch4u32** [doctrine/DoctrineMigrationsBundle#372]
I want to switch from file sessions to db sessions. I following the symfony documentation: https://symfony.com/doc/current/session/database.html

services.yml:

    services:
        Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
            arguments:
                - '%env(DATABASE_URL)%'

framework.yml:

    framework:
        session:
            handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
            cookie_secure: 'auto'
            cookie_samesite: 'lax'
            enabled: true

By running `php bin/console doctrine:migrations:diff` I'm getting the following message:

    Could not find any migrations to execute.

**Comment by goetas** [comment]
`PdoSessionHandler` is something offered by symfony and is not implemented by this bundle.
I think that you should create a ticket on the symfony repo.

**Comment by melroy89** [comment]
Today this is correctly handled I believe by Doctrine: https://symfony.com/doc/current/session.html#preparing-the-database-to-store-sessions
