### ISSUE TITLE
The v2.2 documentation missing

### ISSUE THREAD

**Issue by automatix** [doctrine/DoctrineMigrationsBundle#375]
Hello!

I'm setting up the DoctrineMigrationsBundle in my Symfony project and having an issue with the setting of the correct configration keys and correct value fror them. Normally I would just take a look into the docu. But the docu for the `v2.2` (and btw. for the `v3.0` as well) is missing. The links to it leads to `404` page: https://symfony.com/doc/2.2/bundles/DoctrineMigrationsBundle/index.html.

**Where can I get the docu of the `v2.2` (or at least the correct configs)?**

(Or would it maybe possible to bring the `v2.2` back onto the bundle docu page?)

Thx & regards

**Comment by automatix** [comment]
The `v2.2` docu is [here](https://www.doctrine-project.org/projects/doctrine-migrations-bundle/en/2.2/index.html). Nevertheless it's confusing, that it's missing on the Symfony website.

**Comment by stof** [comment]
@javiereguiluz is this something that needs to be fixed manually by the symfony.com team ?
