### ISSUE TITLE
The v2.2 documentation seems to contain some mistakes

### ISSUE THREAD

**Issue by automatix** [doctrine/DoctrineMigrationsBundle#376]
The ["Configuration" section of the v2.2 documentation](https://www.doctrine-project.org/projects/doctrine-migrations-bundle/en/2.2/index.html#configuration) on doctrine-project.org contains the config key `execution_time_column_name`. Using this leads to an error:

```
In ArrayNode.php line 319:
  Unrecognized option "execution_time_column_name" under "doctrine_migrations.storage.table_storage"
```

The next one (in the same section):

```
    # Deprecated since v2.2, use "storage.table_storage.execution_time_column_name" instead
    executed_at_column_name: 'executed_at'
```

This seems to be a typo. The correct version will be:

```
    # Deprecated since v2.2, use "storage.table_storage.executed_at_column_name" instead
    executed_at_column_name: 'executed_at'
```

**Comment by greg0ire** [comment]
@automatix can you please submit a PR?
