### ISSUE TITLE
Php 8

### ISSUE THREAD

**Issue by ghost** [doctrine/DoctrineMigrationsBundle#388]
Hi 

I want to create a PR for support php 8 I can ?

**Comment by luchaninov** [comment]
duplicate of https://github.com/doctrine/DoctrineMigrationsBundle/issues/362 ?

**Comment by stof** [comment]
I'm closing this as duplicate.

Btw, even the PR already exists at https://github.com/doctrine/DoctrineMigrationsBundle/pull/383 (but it depends on the work being done in the library first)
