### ISSUE TITLE
doctrine:migration:diff  keep on showing the same diff  (options default true for boolean)

### ISSUE THREAD

**Issue by allan-simon** [doctrine/DoctrineMigrationsBundle#397]
versions:

doctrine/dbal: 2.12.1
doctrine/doctrine-bundle: 2.2.2
doctrine/doctrine-migrations-bundle: 3.0.2

I have the following entity

```
/**
 * @ORM\Entity()
 * @ORM\HasLifecycleCallbacks
 *
 */
class Foobar {

    /**
     * blabla some comments (if relevant)
     *
     * @ORM\Column(
     *     type="boolean",
     *     options={"default": "false"}
     * )
     */
    private $isCommon = false;
}
```

And regardless how many times I  `diff` / `migrate` / `diff` / `migrate`  I always end up with this diff

```
$this->addSql('ALTER TABLE foobar ALTER is_common SET DEFAULT \'false\''
```

and in the down 

```
$this->addSql('ALTER TABLE foobar ALTER is_common SET DEFAULT \'false\''
```
(so exactly the two same lines )

**Comment by stof** [comment]
Well, I think you have a mismatch here between a boolean column and a string default. The database probably casts the string provided as default to an actual boolean (but then, be careful whether the string `'false'` gets casted as `true` or `false`). and then, when the DBAL schema tool compares the schema, if finds out that the actual default in the DB does not match the default expected in your mapping `false` is not the same than `'false'`) and updates it.
Try using `options={"default": false}` in your mapping to use a boolean.

In any case, this repository is the wrong issue tracker. DoctrineMigrationsBundle is the wrong repository to report that. The bundle only contains the glue configuration for Symfony projects. Most logic in implemented in `doctrine/migrations` and the schema comparison itself is implemented in `doctrine/dbal` itself.

**Comment by allan-simon** [comment]
indeed,  replacing 'false' by false, fix the problem thanks !
