### ISSUE TITLE
Warning: assert(): assert($doctrine instanceof Registry) failed when you have custom implementation of ManagerRegistry

### ISSUE THREAD

**Issue by slawro** [doctrine/DoctrineMigrationsBundle#400]
after upgrade to version 2.2.2 i get an warning `Warning: assert(): assert($doctrine instanceof Registry)` because we use custom implementation of `Doctrine\Persistence\ManagerRegistry`

in `Doctrine\Bundle\MigrationsBundle\Command\Helper\DoctrineCommandHelper` you should not assert instanceof `Doctrine\Bundle\DoctrineBundle\Registry` but Doctrine\Persistence\ManagerRegistry instead as you only need method `getManagerNames` from this interface

**Comment by nicolas-grekas** [comment]
Can you send a PR please? Branch 2.2.x
