### ISSUE TITLE
Resurrect migration from fixture

### ISSUE THREAD

**Issue by marfillaster** [doctrine/DoctrineMigrationsBundle#41]
This was present in the old version

https://github.com/symfony/symfony/pull/90/files

**Comment by allan-simon** [comment]
can you explain what it was doing ? creating a migration from a fixture ?

**Comment by marfillaster** [comment]
the command `doctrine:migrations:generate:from-data-fixtures` is missing. Not sure if this issue is still valid. This is a 3 year old issue. I suppose I need to close this.
