### ISSUE TITLE
Create doctrine fields from the frontend

### ISSUE THREAD

**Issue by Remonell** [doctrine/DoctrineMigrationsBundle#412]
Hi,

sorry in advance since this is not a bug but more like a general question. I am working on a project with symfony/doctrine in the backend. What I would like to achieve is to have a simple text field in the frontend where I can type in the name of the new field in an entity that already exists. But I don't know if doctrine is even able to do that, since all the other entities and fields are hardcoded in php files. What I would need are functions with parameters for the name, type, size etc.
I am very new to backend development, but I have searched for hours and read a bunch in the doctrine documentation (YAML Schema Files did sound interesting but will not be supported in future versions) without success. My database is MySQL, maybe that is an issue as well?

Hopefully I can get a helpful hint here.

**Comment by greg0ire** [comment]
I think you are looking for: https://symfony.com/doc/current/bundles/SymfonyMakerBundle/index.html

Fair warning though: a lot of Doctrine people think the best way to do this is to avoid getters and setters or at least, add them when strictly necessary. Consider taking the time to do this by hand.
