### ISSUE TITLE
[3.1.0] Doctrine ORM Manager named "" does not exist.

### ISSUE THREAD

**Issue by emodric** [doctrine/DoctrineMigrationsBundle#414]
Hi,

after upgrading this package to v3.1.0, I started getting `Doctrine ORM Manager named "" does not exist.` error when I run my migrations. Downgrading the package to 3.0.2 resolves the error.

I do not use Doctrine ORM in my package and it is not configured, however, it is installed by another dependency.

Relevant stack trace:

```
Exception trace:
  at vendor/doctrine/persistence/lib/Doctrine/Persistence/AbstractManagerRegistry.php:150
 Doctrine\Persistence\AbstractManagerRegistry->getManager() at vendor/doctrine/migrations/lib/Doctrine/Migrations/Configuration/EntityManager/ManagerRegistryEntityManager.php:36
 Doctrine\Migrations\Configuration\EntityManager\ManagerRegistryEntityManager->getEntityManager() at vendor/doctrine/migrations/lib/Doctrine/Migrations/DependencyFactory.php:184
 Doctrine\Migrations\DependencyFactory->getEntityManager() at vendor/doctrine/migrations/lib/Doctrine/Migrations/DependencyFactory.php:169
 Doctrine\Migrations\DependencyFactory->getConnection() at vendor/doctrine/migrations/lib/Doctrine/Migrations/Tools/Console/Command/MigrateCommand.php:133
```

**Comment by brusch** [comment]
Same here, this is currently a breaking change.

**Comment by fashxp** [comment]
Same problem occurs with Pimcore, see https://github.com/pimcore/pimcore/issues/8694

**Comment by greg0ire** [comment]
When you downgrade this package to 3.0.2, is it the only package that gets downgraded?

**Comment by emodric** [comment]
@greg0ire Yep. This is on PHP 8, btw, if its relevant.

**Comment by greg0ire** [comment]
I suspect it has to do with https://github.com/doctrine/DoctrineMigrationsBundle/pull/364 , and that 3.0.3 works too.

**Comment by greg0ire** [comment]
Also probably related to https://github.com/doctrine/DoctrineMigrationsBundle/issues/413, which might be closer to the root cause.

**Comment by goetas** [comment]
The issue seems because of https://github.com/doctrine/DoctrineMigrationsBundle/blob/d1248471734c62b94baac36cb18e9c635775eeb0/DependencyInjection/CompilerPass/ConfigureDependencyFactoryPass.php#L22

Does anyone know a better way to check if doctrine ORM is in use?

**Comment by greg0ire** [comment]
Maybe by checking if this parameter exists: https://github.com/doctrine/DoctrineBundle/blob/a08bc3b4d8567cdff05e89b272ba1e06e9d71c21/DependencyInjection/DoctrineExtension.php#L469 ?

**Comment by fashxp** [comment]
I can confirm that 3.0.3 works for us.

**Comment by goetas** [comment]
Can someone please try https://github.com/doctrine/DoctrineMigrationsBundle/pull/415 ?

A quick way to install it is:
```
composer require doctrine/doctrine-migrations-bundle:dev-prefered-em
```

**Comment by emodric** [comment]
@goetas Working fine :+1:

**Comment by brusch** [comment]
For me as well 👍
