### ISSUE TITLE
SF update : structure of the migrations table

### ISSUE THREAD

**Issue by clem983** [doctrine/DoctrineMigrationsBundle#420]
Hi,

I'm updating a website, which was running Symfony 3.4, to the 4.4 version. But I have a problem concerning migrations.

I began this project with 3.2 version, and, at this moment, migrations were stored with this format :

| version | executed_at |
| 20180310191301 | 2018-03-10 19:13:30 |

After the 3.4 update, the table changed, and I had to add the namespaces, to obtain something like that : 
| version | executed_at | execution_time |
| DoctrineMigrations\Version20180310191301 | 2018-03-10 19:13:30 | 120 |

And now that I'm in 4.4, when I execute a migration, I have an error:

`WARNING! You have 90 previously executed migrations in the database that are not registered migrations.`

... because the syntax with namespaces doesn't seem recognized ! If I execute migrations on an empty database, the table "migrations_versions" is created like it was some months ago (first example). It's not a big problem, but I can't understand why it changes.

If someone could help me ... :)

Thanks a lot !

**Comment by greg0ire** [comment]
:thinking: the upgrade guide mentions running some commands will result in an upgrade of the migration table structure: https://github.com/doctrine/migrations/blob/3.1.x/UPGRADE.md#migrations-table . Also, another command is mentioned, maybe it will help?

**Comment by clem983** [comment]
Thank you for your answer, but it was not working with these commands :)

I solved it, updating symfony/orm-pack to ^2.0. 
I still don't understand why, when my project was in 3.4, with orm-pack ^1.0, it was the second structure ... but now it works ... it's the most important ! :)
