### ISSUE TITLE
MigrationCollector always requires database connection

### ISSUE THREAD

**Issue by ahundiak** [doctrine/DoctrineMigrationsBundle#423]
Maybe it's just me but I find it annoying that the out of the box Symfony website-skeleton requires an actual database connection for the migrations bundle even if no database is currently being used.  I also see plenty of help requests from developers who are stymied when they encounter this sort of error.  Sure they should be able to work around the issue but it is still annoying.

The problem is that the migrations bundle profile data collector always checks for migrations tables which in turn requires a valid connection:
```
# Doctrine\Bundle\MigrationsBundle\Collector\MigrationsCollector
public function collect(Request $request, Response $response, \Throwable $exception = null)
    {
        // Add a data template
        $this->data = [
            'available_migrations' => null,
            'executed_migrations' => null,
            'new_migrations' => null,
            'unavailable_migrations' => null,
            'storage' => null,
            'table' => null,
            'column' => null,
            'driver' => null,
            'name' => null,
            'namespaces' => null,
        ];

        $metadataStorage = $this->dependencyFactory->getMetadataStorage();
        $planCalculator = $this->dependencyFactory->getMigrationPlanCalculator();
        $statusCalculator = $this->dependencyFactory->getMigrationStatusCalculator();

        // Add a try catch
        try {
            $executedMigrations  = $metadataStorage->getExecutedMigrations();
        }
        catch (\Exception $e) { 
            // Basically ignore the data collector
            return;
        }
```
The above proposed fix catches the connection exception and returns an empty data collector.  I suppose there are more sophisticated ways of doing this and using exceptions for flow control is frowned upon but in this case I think it is fine.

Is this the sort of thing for which a PR might be welcomed?  Just a minor improvement for the Developer's UX.

**Comment by stloyd** [comment]
This should be closed:
- PR was merged #428 
- and release `3.2.0` was done
