### ISSUE TITLE
option enable_profiler breaks the new site

### ISSUE THREAD

**Issue by masz** [doctrine/DoctrineMigrationsBundle#433]
Tested on new installation (full) 5.3.3
- extended db version number "serverVersion=mariadb-10.4.20" in .env
- created a new Controller with maker
- created a new Entity with maker
- command line: diff generated, migration executed (all fine)

Browser Test:
 "The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue."

It works without "enable_profiler" option in doctrine_migrations.yaml (db reads/writes are fine as well)

Do you have any suggestion what may be wrong here?

**Comment by goetas** [comment]
@masz did you try to discover which commands is trying to run doctrine? which fields are not up to date?

**Comment by masz** [comment]
@goetas thanks for the hint, my docker setup was overriding the env vars without "mariadb-" in serverVersion.
