### ISSUE TITLE
  join(): Argument #2 ($array) must be of type ?array, string given   

### ISSUE THREAD

**Issue by ej7dev** [doctrine/DoctrineMigrationsBundle#438]

**Comment by greg0ire** [comment]
![https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimages.hellogiggles.com%2Fuploads%2F2015%2F12%2F11%2FGinaGIF.gif&f=1&nofb=1](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimages.hellogiggles.com%2Fuploads%2F2015%2F12%2F11%2FGinaGIF.gif&f=1&nofb=1)
