### ISSUE TITLE
Profiler crashes after update from 3.1.1

### ISSUE THREAD

**Issue by bt-nn** [doctrine/DoctrineMigrationsBundle#467]
Hi,

after `composer update doctrine/doctrine-migrations-bundle` the debug toolbar breaks. I tried 3.2.2 down to 3.1.2 and got always the same error.
![grafik](https://user-images.githubusercontent.com/95690155/152173671-faf2798c-fc3d-44db-bd1a-656e90eb49b6.png)

I use
- symfony: 5.4.3
- doctrine/doctrine-bundle: 2.5.5
- doctrine/orm: 2.9.6

**Comment by derrabus** [comment]
Did you clear the cache after upgrading?

**Comment by bt-nn** [comment]
Yes. Composer clears the cache after the update. But i also ran a c:c manually.
BUT cause of your writing i tried the update again and deleted the cache with rm -rf and that worked.
Thanks
