### ISSUE TITLE
Symfony deprecation

### ISSUE THREAD

**Issue by dannyvw** [doctrine/DoctrineMigrationsBundle#497]
Method "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface::collect()" might add "void" as a native return type declaration in the future. Do the same in implementation "Doctrine\Bundle\MigrationsBundle\Collector\MigrationsCollector" now to avoid errors or add an explicit @return annotation to suppress this message.

**Comment by greg0ire** [comment]
Do you want to send a PR that does this?

**Comment by dannyvw** [comment]
https://github.com/doctrine/DoctrineMigrationsBundle/pull/498
