### ISSUE TITLE
Migrations with addSql in postUp stopped work

### ISSUE THREAD

**Issue by ko4an4ik** [doctrine/DoctrineMigrationsBundle#552]
We encountered the following issue - during the execution of composer update, some of our migrations stopped working correctly.

This is related to this merge request: https://github.com/doctrine/migrations/pull/1432

I might have missed this, but I expected that updating from doctrine/migrations 3.7.4 to 3.8.0 would not introduce any backward-incompatible changes.

In project, we don't have a direct dependency on doctrine/migrations, only on doctrine/doctrine-migrations-bundle. Can you advise on how to properly version the doctrine/doctrine-migrations-bundle package to ensure that I don't get any backward-incompatible changes when running composer update?

Thank you for any response.

**Comment by derrabus** [comment]
Closing as duplicate.
