### ISSUE TITLE
Generated migrations do not consider `columnDefinition=...` clause

### ISSUE THREAD

**Issue by jean553** [doctrine/DoctrineMigrationsBundle#553]
doctrine/doctrine-migrations-bundle 3.3.1

The content of `columnDefinition=...` is not part of the generated migration.

For instance:

```php
 #[ORM\Column(
    type: 'string',
    length: 255,

    // custom column definition content here...
    columnDefinition: "VARCHAR(255) UNIQUE")
]
private string $lastName;
```

When using the `doctrine:migrations:diff` or `doctrine:migrations:migrate`, the generated migration does not contain the custom column definition. According to the documentation [here](https://www.doctrine-project.org/projects/doctrine-orm/en/3.3/reference/attributes-reference.html#column), this custom setting should be set in the migration.

**Comment by stof** [comment]
This bundle is not responsible for the content of migrations. The SQL queries are generated by doctrine/dbal. I suggest you to report it there so that the DBAL maintainers can investigate this

**Comment by jean553** [comment]
Alright, sorry for that, I post this on dbal then.
