### ISSUE TITLE
app/console doctrine:migrations:migrate fails on no migrations

### ISSUE THREAD

**Issue by temp** [doctrine/DoctrineMigrationsBundle#64]
We are using :migrate in a deploy script, and after a transition to a new project structure all of the existing migrations have been deleted.

Problem: app/console doctrine:migrations:migrate fails with an exit code 4 when there are no migrations. 

A solve could be either a command line switch --skip-on-zero or similar, or maybe just exit with 0 in this case. I'm uncertain on wether or not this should be the case. On one hand, if a migrate command has been called with no migrations, this is an error case. On the other hand, if there is simply nothing to do, just do nothing.

**Comment by KingCrunch** [comment]
:+1: 
Should return `0` in every case where there is no migration to perform: It says "I've executed all migrations I could found", which is none in this special case, but still it was successful in doing nothing :smile:

**Comment by jrobeson** [comment]
Shouldn't this issue be solved in the migrations lib itself and not in the bundle command?

**Comment by mikeSimonson** [comment]
It's there https://github.com/doctrine/migrations/pull/150
