### ISSUE TITLE
LatestCommand Issue

### ISSUE THREAD

**Issue by github-scott** [doctrine/DoctrineMigrationsBundle#91]
Since this commit - https://github.com/doctrine/DoctrineMigrationsBundle/commit/bf9bcb39506047de069066ec63f57978f0d7b135

I now get this error:-

PHP Fatal error:  Class 'Doctrine\DBAL\Migrations\Tools\Console\Command\LatestCommand' not found in /...../vendor/doctrine/doctrine-migrations-bundle/Doctrine/Bundle/MigrationsBundle/Command/MigrationsLatestDoctrineCommand.php on line 30

Is there a dependancy required to make sure Doctrine\DBAL\Migrations\Tools\Console\Command\LatestCommand exists?

**Comment by mikeSimonson** [comment]
Closing as it's old and probably fixed by that commit https://github.com/doctrine/DoctrineMigrationsBundle/commit/0a3c3770682ef446f5ca4f7f102d1873494bc197

**Comment by dincho** [comment]
I can confirm that below config works:
```
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "doctrine/doctrine-migrations-bundle": "1.*",
    }
```
